
# Distributed AI Damage Classification Service

## Notebook 01: Dataset Validation

### Goals
1. Access the MBDD2025 building surface defect dataset.
2. Inspect its files and annotation formats.
3. Identify available damage and structural-type labels.
4. Check class distributions and missing annotations.
5. Decide on a reliable training strategy before model development.

**Environment:** Google Colab  
**Stage:** Dataset validation — no model training yet.

In [7]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
# Creating a permanent project workspace
from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/DistributedAIProject")
PROJECT_DIR.mkdir(parents=True, exist_ok=True)

print("Project workspace:", PROJECT_DIR)
print("Workspace exists:", PROJECT_DIR.exists())

Project workspace: /content/drive/MyDrive/DistributedAIProject
Workspace exists: True

In [ ]:
import os
import sys
import platform

In [ ]:
# Checking the runtime
print("Python version: ", sys.version.split()[0])
print("Operating system: ", platform.system())
print("Google Colab runtime: ", "COLAB_RELEASE_TAG" in os.environ)

Python version:  3.13.16
Operating system:  Linux
Google Colab runtime:  True

In [ ]:
# Checking GPU availability
import subprocess
import shutil

In [ ]:
if shutil.which("nvidia-smi") is not None:
  result = subprocess.run(["nvidia-smi"], capture_output=True, text=True)
  print(result.stdout)

else:
  print("nvidia-smi is unavailable.")
  print("Checking whether PyTorch can access a GPU...")

  try:
    import torch
    print("PyTorch version: ", torch.__version__)
    print("CUDA available: ", torch.cuda.is_available())

    if torch.cuda.is_available():
      print("GPU: ", torch.cuda.get_device_name(0))
    else:
      print("No GPU available. CPU is sufficient for dataset inspection.")

  except ImportError:
    print("PyTorch is not installed. No installation is needed yet.")

Wed Oct 28 15:57:27 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
# Installing lightweight inspection tools
%pip -q install requests beautifulsoup4

In [ ]:
# Checking the dataset record
import requests

In [ ]:
recordURL = "https://zenodo.org/api/records/15622584"

response = requests.get(recordURL, timeout=30)
response.raise_for_status()

record = response.json()

print("Dataset title: ", record["metadata"].get("title"))
print("Publication Date: ", record["metadata"].get("publication_date"))

print("\nAvailable files: ")
for i in record.get("files", []):
  print(
      "Name:", i.get("key"), "| Size (bytes):", i.get("size"), "| Download URL:", i.get("links", {}).get("self"))

Dataset title:  MBDD2025: A Deep Learning-Oriented Dataset for Diverse Building Defect Detection from UAV Images
Publication Date:  2025-06-09

Available files:
Name: MBDD2025.zip | Size (bytes): 2533687033 | Download URL: https://zenodo.org/api/records/15622584/files/MBDD2025.zip/content

In [ ]:
# Checking the license and description
metadata = record.get("metadata", {})

print("Description: ")
print(metadata.get("description", "No description provided"))

print("\nLicense information:")
print(metadata.get("license", "No licence field found"))

print("\nKeywords:")
print(metadata.get("keywords", []))

Description:
<p>MBDD2025 is a large-scale dataset of building surface defects collected by UAV imagery. It is designed for object detection and classification tasks in intelligent building inspection. The dataset covers a wide range of structural types and defect categories, making it suitable for deployment in diverse real-world scenarios.<br><br></p>

License information:
{'id': 'cc-by-4.0'}

Keywords:
['Building defect detection', 'Object detection', 'UAV imagery']

In [ ]:
# Checking remote access
import requests

In [ ]:
archiveURL = ("https://zenodo.org/api/records/15622584/"
              "files/MBDD2025.zip/content")
response = requests.head(archiveURL, allow_redirects=True, timeout=30)

In [ ]:
print("HTTP status: ", response.status_code)
print("Content length: ", response.headers.get("Content-Length"))
print("Accept-Ranges: ", response.headers.get("Accept-Ranges"))
print("Final URL: ", response.url)

response.close()

HTTP status:  200
Content length:  2533687033
Accept-Ranges:  None
Final URL:  https://zenodo.org/api/records/15622584/files/MBDD2025.zip/content

In [ ]:
# Checking Colab storage
import shutil

In [ ]:
total, used, free = shutil.disk_usage("/content")
def to_gb(n):
  return n/(1024**3)

print(f"Total disk space: {to_gb(total):.2f} GB")
print(f"Used disk space: {to_gb(total):.2f} GB")
print(f"Free disk space: {to_gb(free):.2f} GB")
print(f"Dataset archive: {2533687033/(1024**3):.2f} GB")

Total disk space: 112.64 GB
Used disk space: 112.64 GB
Free disk space: 70.06 GB
Dataset archive: 2.36 GB

In [ ]:
for i in ["/content", "/tmp"]:
    usage = shutil.disk_usage(i)

    print(f"\nPath: {i}")
    print(f"Total: {usage.total/1024**3:.2f} GiB")
    print(f"Used:  {usage.used/1024**3:.2f} GiB")
    print(f"Free:  {usage.free/1024**3:.2f} GiB")

print("\nDataset archive: approximately 2.36 GiB")

Path: /content
Total: 112.64 GiB
Used:  42.56 GiB
Free:  70.06 GiB

Path: /tmp
Total: 112.64 GiB
Used:  42.56 GiB
Free:  70.06 GiB

Dataset archive: approximately 2.36 GiB

In [12]:
# Downloading MBDD2025
import requests
from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/DistributedAIProject")
PROJECT_DIR.mkdir(parents=True, exist_ok=True)

archive_path = PROJECT_DIR / "MBDD2025.zip"

# Official Zenodo file-download endpoint
download_url = ("https://zenodo.org/records/15622584/files/MBDD2025.zip?download=1")

if archive_path.exists() and archive_path.stat().st_size > 0:
    print("Archive already exists:", archive_path)
    print("Size (GB):", round(archive_path.stat().st_size / 1e9, 2))

else:
    with requests.get(download_url, stream=True, timeout=(30, 120)) as response:
        response.raise_for_status()
        with open(archive_path, "wb") as out:
            for i in response.iter_content(chunk_size=8 * 1024 * 1024):
                if i:
                    out.write(i)
    print("Download complete:", archive_path)
    print("Size (GB):", round(archive_path.stat().st_size / 1e9, 2))

Archive already exists: /content/drive/MyDrive/DistributedAIProject/MBDD2025.zip
Size (GB): 2.53

In [13]:
# Verifying the ZIP
import zipfile
from pathlib import Path

archive_path = Path("/content/drive/MyDrive/DistributedAIProject/MBDD2025.zip")

print("Archive exists:", archive_path.exists())
print("Archive size (GB):", round(archive_path.stat().st_size / 1e9, 2))

with zipfile.ZipFile(archive_path, "r") as f:
    print("ZIP integrity check: ", f.testzip())
    print("Number of XML annotations:", sum(i.startswith("MBDD2025/Annotations/") and i.endswith(".xml") for i in f.namelist()))

Archive exists: True
Archive size (GB): 2.53
ZIP integrity check:  None
Number of XML annotations: 14471

In [ ]:
# Performing an inspection on the ZIP file
import zipfile

In [ ]:
archive_path = "/content/MBDD2025.zip"
with zipfile.ZipFile(archive_path, "r") as f:
  files = f.infolist()
  n = len(files)

  print("Total entries: ", n)
  print("\nFirst 40 archive entries.")

  for i in files[:40]:
    print(i.filename, "|", i.file_size, "bytes")

  print("\nPotential annotation and documentation files:")
  for i in files:
    name = i.filename.lower()
    if (name.endswith((".xml", ".yaml", ".yml", ".txt", ".json")) and any (j in name for j in ("annotation", "label", "class", "readme", "data.yaml", "dataset"))):
      print(i.filename)

Total entries:  43418

First 40 archive entries.
MBDD2025/ | 0 bytes
MBDD2025/Annotations/ | 0 bytes
MBDD2025/Annotations/Hefei1.xml | 775 bytes
MBDD2025/Annotations/Hefei10.xml | 776 bytes
MBDD2025/Annotations/Hefei100.xml | 2423 bytes
MBDD2025/Annotations/Hefei1000.xml | 1187 bytes
MBDD2025/Annotations/Hefei10000.xml | 1575 bytes
MBDD2025/Annotations/Hefei10001.xml | 1983 bytes
MBDD2025/Annotations/Hefei10002.xml | 3612 bytes
MBDD2025/Annotations/Hefei10003.xml | 4043 bytes
MBDD2025/Annotations/Hefei10004.xml | 1578 bytes
MBDD2025/Annotations/Hefei10005.xml | 2812 bytes
MBDD2025/Annotations/Hefei10006.xml | 3214 bytes
MBDD2025/Annotations/Hefei10007.xml | 3228 bytes
MBDD2025/Annotations/Hefei10008.xml | 4860 bytes
MBDD2025/Annotations/Hefei10009.xml | 3628 bytes
MBDD2025/Annotations/Hefei1001.xml | 1188 bytes
MBDD2025/Annotations/Hefei10010.xml | 4848 bytes
MBDD2025/Annotations/Hefei10011.xml | 5657 bytes
MBDD2025/Annotations/Hefei10012.xml | 5254 bytes
MBDD2025/Annotations/Hefei10013.xml | 5663 bytes
MBDD2025/Annotations/Hefei10014.xml | 6083 bytes
MBDD2025/Annotations/Hefei10015.xml | 5255 bytes
MBDD2025/Annotations/Hefei10016.xml | 5257 bytes
MBDD2025/Annotations/Hefei10017.xml | 5264 bytes
MBDD2025/Annotations/Hefei10018.xml | 5669 bytes
MBDD2025/Annotations/Hefei10019.xml | 5238 bytes
MBDD2025/Annotations/Hefei1002.xml | 1188 bytes
MBDD2025/Annotations/Hefei10020.xml | 4024 bytes
MBDD2025/Annotations/Hefei10021.xml | 4022 bytes
MBDD2025/Annotations/Hefei10022.xml | 2393 bytes
MBDD2025/Annotations/Hefei10023.xml | 2392 bytes
MBDD2025/Annotations/Hefei10024.xml | 1987 bytes
MBDD2025/Annotations/Hefei10025.xml | 1985 bytes
MBDD2025/Annotations/Hefei10026.xml | 3210 bytes
MBDD2025/Annotations/Hefei10027.xml | 4039 bytes
MBDD2025/Annotations/Hefei10028.xml | 6068 bytes
MBDD2025/Annotations/Hefei10029.xml | 5663 bytes
MBDD2025/Annotations/Hefei1003.xml | 1189 bytes
MBDD2025/Annotations/Hefei10030.xml | 5260 bytes

Potential annotation and documentation files:
MBDD2025/Annotations/Hefei1.xml
MBDD2025/Annotations/Hefei10.xml
MBDD2025/Annotations/Hefei100.xml
MBDD2025/Annotations/Hefei1000.xml
MBDD2025/Annotations/Hefei10000.xml
MBDD2025/Annotations/Hefei10001.xml
MBDD2025/Annotations/Hefei10002.xml
MBDD2025/Annotations/Hefei10003.xml
MBDD2025/Annotations/Hefei10004.xml
MBDD2025/Annotations/Hefei10005.xml
MBDD2025/Annotations/Hefei10006.xml
MBDD2025/Annotations/Hefei10007.xml
MBDD2025/Annotations/Hefei10008.xml
MBDD2025/Annotations/Hefei10009.xml
MBDD2025/Annotations/Hefei1001.xml
MBDD2025/Annotations/Hefei10010.xml
MBDD2025/Annotations/Hefei10011.xml
MBDD2025/Annotations/Hefei10012.xml
MBDD2025/Annotations/Hefei10013.xml
MBDD2025/Annotations/Hefei10014.xml
MBDD2025/Annotations/Hefei10015.xml
MBDD2025/Annotations/Hefei10016.xml
MBDD2025/Annotations/Hefei10017.xml
MBDD2025/Annotations/Hefei10018.xml
MBDD2025/Annotations/Hefei10019.xml
MBDD2025/Annotations/Hefei1002.xml
MBDD2025/Annotations/Hefei10020.xml
MBDD2025/Annotations/Hefei10021.xml
MBDD2025/Annotations/Hefei10022.xml
MBDD2025/Annotations/Hefei10023.xml
MBDD2025/Annotations/Hefei10024.xml
MBDD2025/Annotations/Hefei10025.xml
MBDD2025/Annotations/Hefei10026.xml
MBDD2025/Annotations/Hefei10027.xml
MBDD2025/Annotations/Hefei10028.xml
MBDD2025/Annotations/Hefei10029.xml
MBDD2025/Annotations/Hefei1003.xml
MBDD2025/Annotations/Hefei10030.xml
MBDD2025/Annotations/Hefei10031.xml
MBDD2025/Annotations/Hefei10032.xml
MBDD2025/Annotations/Hefei10033.xml
MBDD2025/Annotations/Hefei10034.xml
MBDD2025/Annotations/Hefei10035.xml
MBDD2025/Annotations/Hefei10036.xml
MBDD2025/Annotations/Hefei10037.xml
MBDD2025/Annotations/Hefei10038.xml
MBDD2025/Annotations/Hefei10039.xml
MBDD2025/Annotations/Hefei1004.xml
MBDD2025/Annotations/Hefei10040.xml
MBDD2025/Annotations/Hefei10041.xml
MBDD2025/Annotations/Hefei10042.xml
MBDD2025/Annotations/Hefei10043.xml
MBDD2025/Annotations/Hefei10044.xml
MBDD2025/Annotations/Hefei10045.xml
MBDD2025/Annotations/Hefei10046.xml
MBDD2025/Annotations/Hefei10047.xml
MBDD2025/Annotations/Hefei10048.xml
MBDD2025/Annotations/Hefei10049.xml
MBDD2025/Annotations/Hefei1005.xml
MBDD2025/Annotations/Hefei10050.xml
MBDD2025/Annotations/Hefei10051.xml
MBDD2025/Annotations/Hefei10052.xml
MBDD2025/Annotations/Hefei10053.xml
MBDD2025/Annotations/Hefei10054.xml
MBDD2025/Annotations/Hefei10055.xml
MBDD2025/Annotations/Hefei10056.xml
MBDD2025/Annotations/Hefei10057.xml
MBDD2025/Annotations/Hefei10058.xml
MBDD2025/Annotations/Hefei10059.xml
MBDD2025/Annotations/Hefei1006.xml
MBDD2025/Annotations/Hefei10060.xml
MBDD2025/Annotations/Hefei10061.xml
MBDD2025/Annotations/Hefei10062.xml
MBDD2025/Annotations/Hefei10063.xml
MBDD2025/Annotations/Hefei10064.xml
MBDD2025/Annotations/Hefei10065.xml
MBDD2025/Annotations/Hefei10066.xml
MBDD2025/Annotations/Hefei10067.xml
MBDD2025/Annotations/Hefei10068.xml
MBDD2025/Annotations/Hefei10069.xml
MBDD2025/Annotations/Hefei1007.xml
MBDD2025/Annotations/Hefei10070.xml
MBDD2025/Annotations/Hefei10071.xml
MBDD2025/Annotations/Hefei10072.xml
MBDD2025/Annotations/Hefei10073.xml
MBDD2025/Annotations/Hefei10074.xml
MBDD2025/Annotations/Hefei10075.xml
MBDD2025/Annotations/Hefei10076.xml
MBDD2025/Annotations/Hefei10077.xml
MBDD2025/Annotations/Hefei10078.xml
MBDD2025/Annotations/Hefei10079.xml
MBDD2025/Annotations/Hefei1008.xml
MBDD2025/Annotations/Hefei10080.xml
MBDD2025/Annotations/Hefei10081.xml
MBDD2025/Annotations/Hefei10082.xml
MBDD2025/Annotations/Hefei10083.xml
MBDD2025/Annotations/Hefei10084.xml
MBDD2025/Annotations/Hefei10085.xml
MBDD2025/Annotations/Hefei10086.xml
MBDD2025/Annotations/Hefei10087.xml
MBDD2025/Annotations/Hefei10088.xml
MBDD2025/Annotations/Hefei10089.xml
MBDD2025/Annotations/Hefei1009.xml
MBDD2025/Annotations/Hefei10090.xml
MBDD2025/Annotations/Hefei10091.xml
MBDD2025/Annotations/Hefei10092.xml
MBDD2025/Annotations/Hefei10093.xml
MBDD2025/Annotations/Hefei10094.xml
MBDD2025/Annotations/Hefei10095.xml
MBDD2025/Annotations/Hefei10096.xml
MBDD2025/Annotations/Hefei10097.xml
MBDD2025/Annotations/Hefei10098.xml
MBDD2025/Annotations/Hefei10099.xml
MBDD2025/Annotations/Hefei101.xml
MBDD2025/Annotations/Hefei1010.xml
MBDD2025/Annotations/Hefei10100.xml
MBDD2025/Annotations/Hefei10101.xml
MBDD2025/Annotations/Hefei10102.xml
MBDD2025/Annotations/Hefei10103.xml
MBDD2025/Annotations/Hefei10104.xml
MBDD2025/Annotations/Hefei10105.xml
MBDD2025/Annotations/Hefei10106.xml
MBDD2025/Annotations/Hefei10107.xml
MBDD2025/Annotations/Hefei10108.xml
MBDD2025/Annotations/Hefei10109.xml
MBDD2025/Annotations/Hefei1011.xml
MBDD2025/Annotations/Hefei10110.xml
MBDD2025/Annotations/Hefei10111.xml
MBDD2025/Annotations/Hefei10112.xml
MBDD2025/Annotations/Hefei10113.xml
MBDD2025/Annotations/Hefei10114.xml
MBDD2025/Annotations/Hefei10115.xml
MBDD2025/Annotations/Hefei10116.xml
MBDD2025/Annotations/Hefei10117.xml
MBDD2025/Annotations/Hefei10118.xml
MBDD2025/Annotations/Hefei10119.xml
MBDD2025/Annotations/Hefei1012.xml
MBDD2025/Annotations/Hefei10120.xml
MBDD2025/Annotations/Hefei10121.xml
MBDD2025/Annotations/Hefei10122.xml
MBDD2025/Annotations/Hefei10123.xml
MBDD2025/Annotations/Hefei10124.xml
MBDD2025/Annotations/Hefei10125.xml
MBDD2025/Annotations/Hefei10126.xml
MBDD2025/Annotations/Hefei10127.xml
MBDD2025/Annotations/Hefei10128.xml
MBDD2025/Annotations/Hefei10129.xml
MBDD2025/Annotations/Hefei1013.xml
MBDD2025/Annotations/Hefei10130.xml
MBDD2025/Annotations/Hefei10131.xml
MBDD2025/Annotations/Hefei10132.xml
MBDD2025/Annotations/Hefei10133.xml
MBDD2025/Annotations/Hefei10134.xml
MBDD2025/Annotations/Hefei10135.xml
MBDD2025/Annotations/Hefei10136.xml
MBDD2025/Annotations/Hefei10137.xml
MBDD2025/Annotations/Hefei10138.xml
MBDD2025/Annotations/Hefei10139.xml
MBDD2025/Annotations/Hefei1014.xml
MBDD2025/Annotations/Hefei10140.xml
MBDD2025/Annotations/Hefei10141.xml
MBDD2025/Annotations/Hefei10142.xml
MBDD2025/Annotations/Hefei10143.xml
MBDD2025/Annotations/Hefei10144.xml
MBDD2025/Annotations/Hefei10145.xml
MBDD2025/Annotations/Hefei10146.xml
MBDD2025/Annotations/Hefei10147.xml
MBDD2025/Annotations/Hefei10148.xml
MBDD2025/Annotations/Hefei10149.xml
MBDD2025/Annotations/Hefei1015.xml
MBDD2025/Annotations/Hefei10150.xml
MBDD2025/Annotations/Hefei10151.xml
MBDD2025/Annotations/Hefei10152.xml
MBDD2025/Annotations/Hefei10153.xml
MBDD2025/Annotations/Hefei10154.xml
MBDD2025/Annotations/Hefei10155.xml
MBDD2025/Annotations/Hefei10156.xml
MBDD2025/Annotations/Hefei10157.xml
MBDD2025/Annotations/Hefei10158.xml
MBDD2025/Annotations/Hefei10159.xml
MBDD2025/Annotations/Hefei1016.xml
MBDD2025/Annotations/Hefei10160.xml
MBDD2025/Annotations/Hefei10161.xml
MBDD2025/Annotations/Hefei10162.xml
MBDD2025/Annotations/Hefei10163.xml
MBDD2025/Annotations/Hefei10164.xml
MBDD2025/Annotations/Hefei10165.xml
MBDD2025/Annotations/Hefei10166.xml
MBDD2025/Annotations/Hefei10167.xml
MBDD2025/Annotations/Hefei10168.xml
MBDD2025/Annotations/Hefei10169.xml
MBDD2025/Annotations/Hefei1017.xml
MBDD2025/Annotations/Hefei10170.xml
MBDD2025/Annotations/Hefei10171.xml
MBDD2025/Annotations/Hefei10172.xml
MBDD2025/Annotations/Hefei10173.xml
MBDD2025/Annotations/Hefei10174.xml
MBDD2025/Annotations/Hefei10175.xml
MBDD2025/Annotations/Hefei10176.xml
MBDD2025/Annotations/Hefei10177.xml
MBDD2025/Annotations/Hefei10178.xml
MBDD2025/Annotations/Hefei10179.xml
MBDD2025/Annotations/Hefei1018.xml
MBDD2025/Annotations/Hefei10180.xml
MBDD2025/Annotations/Hefei10181.xml
MBDD2025/Annotations/Hefei10182.xml
MBDD2025/Annotations/Hefei10183.xml
MBDD2025/Annotations/Hefei10184.xml
MBDD2025/Annotations/Hefei10185.xml
MBDD2025/Annotations/Hefei10186.xml
MBDD2025/Annotations/Hefei10187.xml
MBDD2025/Annotations/Hefei10188.xml
MBDD2025/Annotations/Hefei10189.xml
MBDD2025/Annotations/Hefei1019.xml
MBDD2025/Annotations/Hefei10190.xml
MBDD2025/Annotations/Hefei10191.xml
MBDD2025/Annotations/Hefei10192.xml
MBDD2025/Annotations/Hefei10193.xml
MBDD2025/Annotations/Hefei10194.xml
MBDD2025/Annotations/Hefei10195.xml
MBDD2025/Annotations/Hefei10196.xml
MBDD2025/Annotations/Hefei10197.xml
MBDD2025/Annotations/Hefei10198.xml
MBDD2025/Annotations/Hefei10199.xml
MBDD2025/Annotations/Hefei102.xml
MBDD2025/Annotations/Hefei1020.xml
MBDD2025/Annotations/Hefei10200.xml
MBDD2025/Annotations/Hefei10201.xml
MBDD2025/Annotations/Hefei10202.xml
MBDD2025/Annotations/Hefei10203.xml
MBDD2025/Annotations/Hefei10204.xml
MBDD2025/Annotations/Hefei10205.xml
MBDD2025/Annotations/Hefei10206.xml
MBDD2025/Annotations/Hefei10207.xml
MBDD2025/Annotations/Hefei10208.xml
MBDD2025/Annotations/Hefei10209.xml
MBDD2025/Annotations/Hefei1021.xml
MBDD2025/Annotations/Hefei10210.xml
MBDD2025/Annotations/Hefei10211.xml
MBDD2025/Annotations/Hefei10212.xml
MBDD2025/Annotations/Hefei10213.xml
MBDD2025/Annotations/Hefei10214.xml
MBDD2025/Annotations/Hefei10215.xml
MBDD2025/Annotations/Hefei10216.xml
MBDD2025/Annotations/Hefei10217.xml
MBDD2025/Annotations/Hefei10218.xml
MBDD2025/Annotations/Hefei10219.xml
MBDD2025/Annotations/Hefei1022.xml
MBDD2025/Annotations/Hefei10220.xml
MBDD2025/Annotations/Hefei10221.xml
MBDD2025/Annotations/Hefei10222.xml
MBDD2025/Annotations/Hefei10223.xml
MBDD2025/Annotations/Hefei10224.xml
MBDD2025/Annotations/Hefei10225.xml
MBDD2025/Annotations/Hefei10226.xml
MBDD2025/Annotations/Hefei10227.xml
MBDD2025/Annotations/Hefei10228.xml
MBDD2025/Annotations/Hefei10229.xml
MBDD2025/Annotations/Hefei1023.xml
MBDD2025/Annotations/Hefei10230.xml
MBDD2025/Annotations/Hefei10231.xml
MBDD2025/Annotations/Hefei10232.xml
MBDD2025/Annotations/Hefei10233.xml
MBDD2025/Annotations/Hefei10234.xml
MBDD2025/Annotations/Hefei10235.xml
MBDD2025/Annotations/Hefei10236.xml
MBDD2025/Annotations/Hefei10237.xml
MBDD2025/Annotations/Hefei10238.xml
MBDD2025/Annotations/Hefei10239.xml
MBDD2025/Annotations/Hefei1024.xml
MBDD2025/Annotations/Hefei10240.xml
MBDD2025/Annotations/Hefei10241.xml
MBDD2025/Annotations/Hefei10242.xml
MBDD2025/Annotations/Hefei10243.xml
MBDD2025/Annotations/Hefei10244.xml
MBDD2025/Annotations/Hefei10245.xml
MBDD2025/Annotations/Hefei10246.xml
MBDD2025/Annotations/Hefei10247.xml
MBDD2025/Annotations/Hefei10248.xml
MBDD2025/Annotations/Hefei10249.xml
MBDD2025/Annotations/Hefei1025.xml
MBDD2025/Annotations/Hefei10250.xml
MBDD2025/Annotations/Hefei10251.xml
MBDD2025/Annotations/Hefei10252.xml
MBDD2025/Annotations/Hefei10253.xml
MBDD2025/Annotations/Hefei10254.xml
MBDD2025/Annotations/Hefei10255.xml
MBDD2025/Annotations/Hefei10256.xml
MBDD2025/Annotations/Hefei10257.xml
MBDD2025/Annotations/Hefei10258.xml
MBDD2025/Annotations/Hefei10259.xml
MBDD2025/Annotations/Hefei1026.xml
MBDD2025/Annotations/Hefei10260.xml
MBDD2025/Annotations/Hefei10261.xml
MBDD2025/Annotations/Hefei10262.xml
MBDD2025/Annotations/Hefei10263.xml
MBDD2025/Annotations/Hefei10264.xml
MBDD2025/Annotations/Hefei10265.xml
MBDD2025/Annotations/Hefei10266.xml
MBDD2025/Annotations/Hefei10267.xml
MBDD2025/Annotations/Hefei10268.xml
MBDD2025/Annotations/Hefei10269.xml
MBDD2025/Annotations/Hefei1027.xml
MBDD2025/Annotations/Hefei10270.xml
MBDD2025/Annotations/Hefei10271.xml
MBDD2025/Annotations/Hefei10272.xml
MBDD2025/Annotations/Hefei10273.xml
MBDD2025/Annotations/Hefei10274.xml
MBDD2025/Annotations/Hefei10275.xml
MBDD2025/Annotations/Hefei10276.xml
MBDD2025/Annotations/Hefei10277.xml
MBDD2025/Annotations/Hefei10278.xml
MBDD2025/Annotations/Hefei10279.xml
MBDD2025/Annotations/Hefei1028.xml
MBDD2025/Annotations/Hefei10280.xml
MBDD2025/Annotations/Hefei10281.xml
MBDD2025/Annotations/Hefei10282.xml
MBDD2025/Annotations/Hefei10283.xml
MBDD2025/Annotations/Hefei10284.xml
MBDD2025/Annotations/Hefei10285.xml
MBDD2025/Annotations/Hefei10286.xml
MBDD2025/Annotations/Hefei10287.xml
MBDD2025/Annotations/Hefei10288.xml
MBDD2025/Annotations/Hefei10289.xml
MBDD2025/Annotations/Hefei1029.xml
MBDD2025/Annotations/Hefei10290.xml
MBDD2025/Annotations/Hefei10291.xml
MBDD2025/Annotations/Hefei10292.xml
MBDD2025/Annotations/Hefei10293.xml
MBDD2025/Annotations/Hefei10294.xml
MBDD2025/Annotations/Hefei10295.xml
MBDD2025/Annotations/Hefei10296.xml
MBDD2025/Annotations/Hefei10297.xml
MBDD2025/Annotations/Hefei10298.xml
MBDD2025/Annotations/Hefei10299.xml
MBDD2025/Annotations/Hefei103.xml
MBDD2025/Annotations/Hefei1030.xml
MBDD2025/Annotations/Hefei10300.xml
MBDD2025/Annotations/Hefei10301.xml
MBDD2025/Annotations/Hefei10302.xml
MBDD2025/Annotations/Hefei10303.xml
MBDD2025/Annotations/Hefei10304.xml
MBDD2025/Annotations/Hefei10305.xml
MBDD2025/Annotations/Hefei10306.xml
MBDD2025/Annotations/Hefei10307.xml
MBDD2025/Annotations/Hefei10308.xml
MBDD2025/Annotations/Hefei10309.xml
MBDD2025/Annotations/Hefei1031.xml
MBDD2025/Annotations/Hefei10310.xml
MBDD2025/Annotations/Hefei10311.xml
MBDD2025/Annotations/Hefei10312.xml
MBDD2025/Annotations/Hefei10313.xml
MBDD2025/Annotations/Hefei10314.xml
MBDD2025/Annotations/Hefei10315.xml
MBDD2025/Annotations/Hefei10316.xml
MBDD2025/Annotations/Hefei10317.xml
MBDD2025/Annotations/Hefei10318.xml
MBDD2025/Annotations/Hefei10319.xml
MBDD2025/Annotations/Hefei1032.xml
MBDD2025/Annotations/Hefei10320.xml
MBDD2025/Annotations/Hefei10321.xml
MBDD2025/Annotations/Hefei10322.xml
MBDD2025/Annotations/Hefei10323.xml
MBDD2025/Annotations/Hefei10324.xml
MBDD2025/Annotations/Hefei10325.xml
MBDD2025/Annotations/Hefei10326.xml
MBDD2025/Annotations/Hefei10327.xml
MBDD2025/Annotations/Hefei10328.xml
MBDD2025/Annotations/Hefei10329.xml
MBDD2025/Annotations/Hefei1033.xml
MBDD2025/Annotations/Hefei10330.xml
MBDD2025/Annotations/Hefei10331.xml
MBDD2025/Annotations/Hefei10332.xml
MBDD2025/Annotations/Hefei10333.xml
MBDD2025/Annotations/Hefei10334.xml
MBDD2025/Annotations/Hefei10335.xml
MBDD2025/Annotations/Hefei10336.xml
MBDD2025/Annotations/Hefei10337.xml
MBDD2025/Annotations/Hefei10338.xml
MBDD2025/Annotations/Hefei10339.xml
MBDD2025/Annotations/Hefei1034.xml
MBDD2025/Annotations/Hefei10340.xml
MBDD2025/Annotations/Hefei10341.xml
MBDD2025/Annotations/Hefei10342.xml
MBDD2025/Annotations/Hefei10343.xml
MBDD2025/Annotations/Hefei10344.xml
MBDD2025/Annotations/Hefei10345.xml
MBDD2025/Annotations/Hefei10346.xml
MBDD2025/Annotations/Hefei10347.xml
MBDD2025/Annotations/Hefei10348.xml
MBDD2025/Annotations/Hefei10349.xml
MBDD2025/Annotations/Hefei1035.xml
MBDD2025/Annotations/Hefei10350.xml
MBDD2025/Annotations/Hefei10351.xml
MBDD2025/Annotations/Hefei10352.xml
MBDD2025/Annotations/Hefei10353.xml
MBDD2025/Annotations/Hefei10354.xml
MBDD2025/Annotations/Hefei10355.xml
MBDD2025/Annotations/Hefei10356.xml
MBDD2025/Annotations/Hefei10357.xml
MBDD2025/Annotations/Hefei10358.xml
MBDD2025/Annotations/Hefei10359.xml
MBDD2025/Annotations/Hefei1036.xml
MBDD2025/Annotations/Hefei10360.xml
MBDD2025/Annotations/Hefei10361.xml
MBDD2025/Annotations/Hefei10362.xml
MBDD2025/Annotations/Hefei10363.xml
MBDD2025/Annotations/Hefei10364.xml
MBDD2025/Annotations/Hefei10365.xml
MBDD2025/Annotations/Hefei10366.xml
MBDD2025/Annotations/Hefei10367.xml
MBDD2025/Annotations/Hefei10368.xml
MBDD2025/Annotations/Hefei10369.xml
MBDD2025/Annotations/Hefei1037.xml
MBDD2025/Annotations/Hefei10370.xml
MBDD2025/Annotations/Hefei10371.xml
MBDD2025/Annotations/Hefei10372.xml
MBDD2025/Annotations/Hefei10373.xml
MBDD2025/Annotations/Hefei10374.xml
MBDD2025/Annotations/Hefei10375.xml
MBDD2025/Annotations/Hefei10376.xml
MBDD2025/Annotations/Hefei10377.xml
MBDD2025/Annotations/Hefei10378.xml
MBDD2025/Annotations/Hefei10379.xml
MBDD2025/Annotations/Hefei1038.xml
MBDD2025/Annotations/Hefei10380.xml
MBDD2025/Annotations/Hefei10381.xml
MBDD2025/Annotations/Hefei10382.xml
MBDD2025/Annotations/Hefei10383.xml
MBDD2025/Annotations/Hefei10384.xml
MBDD2025/Annotations/Hefei10385.xml
MBDD2025/Annotations/Hefei10386.xml
MBDD2025/Annotations/Hefei10387.xml
MBDD2025/Annotations/Hefei10388.xml
MBDD2025/Annotations/Hefei10389.xml
MBDD2025/Annotations/Hefei1039.xml
MBDD2025/Annotations/Hefei10390.xml
MBDD2025/Annotations/Hefei10391.xml
MBDD2025/Annotations/Hefei10392.xml
MBDD2025/Annotations/Hefei10393.xml
MBDD2025/Annotations/Hefei10394.xml
MBDD2025/Annotations/Hefei10395.xml
MBDD2025/Annotations/Hefei10396.xml
MBDD2025/Annotations/Hefei10397.xml
MBDD2025/Annotations/Hefei10398.xml
MBDD2025/Annotations/Hefei10399.xml
MBDD2025/Annotations/Hefei104.xml
MBDD2025/Annotations/Hefei1040.xml
MBDD2025/Annotations/Hefei10400.xml
MBDD2025/Annotations/Hefei10401.xml
MBDD2025/Annotations/Hefei10402.xml
MBDD2025/Annotations/Hefei10403.xml
MBDD2025/Annotations/Hefei10404.xml
MBDD2025/Annotations/Hefei10405.xml
MBDD2025/Annotations/Hefei10406.xml
MBDD2025/Annotations/Hefei10407.xml
MBDD2025/Annotations/Hefei10408.xml
MBDD2025/Annotations/Hefei10409.xml
MBDD2025/Annotations/Hefei1041.xml
MBDD2025/Annotations/Hefei10410.xml
MBDD2025/Annotations/Hefei10411.xml
MBDD2025/Annotations/Hefei10412.xml
MBDD2025/Annotations/Hefei10413.xml
MBDD2025/Annotations/Hefei10414.xml
MBDD2025/Annotations/Hefei10415.xml
MBDD2025/Annotations/Hefei10416.xml
MBDD2025/Annotations/Hefei10417.xml
MBDD2025/Annotations/Hefei10418.xml
MBDD2025/Annotations/Hefei10419.xml
MBDD2025/Annotations/Hefei1042.xml
MBDD2025/Annotations/Hefei10420.xml
MBDD2025/Annotations/Hefei10421.xml
MBDD2025/Annotations/Hefei10422.xml
MBDD2025/Annotations/Hefei10423.xml
MBDD2025/Annotations/Hefei10424.xml
MBDD2025/Annotations/Hefei10425.xml
MBDD2025/Annotations/Hefei10426.xml
MBDD2025/Annotations/Hefei10427.xml
MBDD2025/Annotations/Hefei10428.xml
MBDD2025/Annotations/Hefei10429.xml
MBDD2025/Annotations/Hefei1043.xml
MBDD2025/Annotations/Hefei10430.xml
MBDD2025/Annotations/Hefei10431.xml
MBDD2025/Annotations/Hefei10432.xml
MBDD2025/Annotations/Hefei10433.xml
MBDD2025/Annotations/Hefei10434.xml
MBDD2025/Annotations/Hefei10435.xml
MBDD2025/Annotations/Hefei10436.xml
MBDD2025/Annotations/Hefei10437.xml
MBDD2025/Annotations/Hefei10438.xml
MBDD2025/Annotations/Hefei10439.xml
MBDD2025/Annotations/Hefei1044.xml
MBDD2025/Annotations/Hefei10440.xml
MBDD2025/Annotations/Hefei10441.xml
MBDD2025/Annotations/Hefei10442.xml
MBDD2025/Annotations/Hefei10443.xml
MBDD2025/Annotations/Hefei10444.xml
MBDD2025/Annotations/Hefei10445.xml
MBDD2025/Annotations/Hefei10446.xml
MBDD2025/Annotations/Hefei10447.xml
MBDD2025/Annotations/Hefei10448.xml

In [ ]:
# Inspecting one XML annotation
from pathlib import Path
archive_path = "/content/MBDD2025.zip"

with zipfile.ZipFile(archive_path, "r") as f:
  xml_path = "MBDD2025/Annotations/Hefei100.xml"
  xml_content = f.read(xml_path).decode("utf-8", errors="replace")

print(xml_content)

<?xml version='1.0' encoding='utf-8'?>
<annotation>
  <folder>/dji</folder>
  <filename>100.jpg</filename>
  <source>
    <database>Unknown</database>
    <annotation>Unknown</annotation>
    <image>Unknown</image>
  </source>
  <size>
    <width>1280</width>
    <height>720</height>
    <depth />
  </size>
  <segmented>0</segmented>
  <object>
    <name>corrosion</name>
    <truncated>0</truncated>
    <occluded>0</occluded>
    <difficult>0</difficult>
    <bndbox>
      <xmin>2.38</xmin>
      <ymin>174.69</ymin>
      <xmax>44.21</xmax>
      <ymax>290.87</ymax>
    </bndbox>
    <attributes>
      <attribute>
        <name>rotation</name>
        <value>0.0</value>
      </attribute>
    </attributes>
  </object>
  <object>
    <name>corrosion</name>
    <truncated>0</truncated>
    <occluded>0</occluded>
    <difficult>0</difficult>
    <bndbox>
      <xmin>93.01</xmin>
      <ymin>243.24</ymin>
      <xmax>242.89</xmax>
      <ymax>293.2</ymax>
    </bndbox>
    <attributes>
      <attribute>
        <name>rotation</name>
        <value>0.0</value>
      </attribute>
    </attributes>
  </object>
  <object>
    <name>corrosion</name>
    <truncated>0</truncated>
    <occluded>0</occluded>
    <difficult>0</difficult>
    <bndbox>
      <xmin>290.53</xmin>
      <ymin>207.22</ymin>
      <xmax>335.84</xmax>
      <ymax>246.72</ymax>
    </bndbox>
    <attributes>
      <attribute>
        <name>rotation</name>
        <value>0.0</value>
      </attribute>
    </attributes>
  </object>
  <object>
    <name>corrosion</name>
    <truncated>0</truncated>
    <occluded>0</occluded>
    <difficult>0</difficult>
    <bndbox>
      <xmin>635.6</xmin>
      <ymin>209.54</ymin>
      <xmax>691.37</xmax>
      <ymax>254.86</ymax>
    </bndbox>
    <attributes>
      <attribute>
        <name>rotation</name>
        <value>0.0</value>
      </attribute>
    </attributes>
  </object>
  <object>
    <name>corrosion</name>
    <truncated>0</truncated>
    <occluded>0</occluded>
    <difficult>0</difficult>
    <bndbox>
      <xmin>722.74</xmin>
      <ymin>243.24</ymin>
      <xmax>765.73</xmax>
      <ymax>288.55</ymax>
    </bndbox>
    <attributes>
      <attribute>
        <name>rotation</name>
        <value>0.0</value>
      </attribute>
    </attributes>
  </object>
</annotation>

In [ ]:
# Discovering all damage classes
import xml.etree.ElementTree as ET
from collections import Counter

archive_path = "/content/MBDD2025.zip"

damageCounts = Counter()
annotationCount = 0
objects_without_labels = 0
xml_errors = 0

with zipfile.ZipFile(archive_path, "r") as f:
  xmlFiles = [i for i in f.namelist() if i.lower().endswith(".xml") and "/annotations/" in i.lower()]
  for j in xmlFiles:
    try:
      root = ET.fromstring(f.read(j))
      annotationCount = annotationCount+1
      for k in root.findall("object"):
        label = k.findtext("name", default="").strip()
        if label:
          damageCounts[label] = damageCounts[label]+1
        else:
          objects_without_labels = objects_without_labels+1

    except ET.ParseError:
      xml_errors = xml_errors+1

print("XML annotation files processed: ", annotationCount)
print("XML parsing errors: ", xml_errors)
print("Objects without labels: ", objects_without_labels)

print("\nDamage classes and object counts: ")
for label, count in damageCounts.most_common():
  print(f"{label}: {count:,}")

print("\nTotal annotated objects: ", sum(damageCounts.values()))

XML annotation files processed:  14471
XML parsing errors:  0
Objects without labels:  0

Damage classes and object counts:
abscission: 22,702
crack: 17,044
corrosion: 9,207
leakage: 6,642
bulge: 2,018

Total annotated objects:  57613

In [ ]:
with zipfile.ZipFile(archive_path, "r") as f:
  names = f.namelist()

  print("TOP-LEVEL CONTENTS")
  top_level = sorted({i.split("/")[1] for i in names if i.startswith("MBDD2025/") and len(i.split("/"))>2})
  for i in top_level:
    print("-", i)

  print("\nREADME / METADATA FILES")
  docs = [i for i in names if i.lower().endswith(("readme.md", "readme.txt", "metadata.json", "data.yaml")) and not i.endswith("/")]
  for i in docs:
    print(f"\n--- {i} ---")
    try:
      content = f.read(i).decode("utf-8", errors="replace")
      print(content[:8000])
    except Exception as e:
      print("Could not read: ", e)

TOP-LEVEL CONTENTS
- Annotations
- JPEGImages
- Labels

README / METADATA FILES

--- MBDD2025/README.md ---
# MBDD2025: A Deep Learning-Oriented Dataset for Diverse Building Defect Detection from UAV Images

## 📂 Dataset Overview

**MBDD2025** is a large-scale dataset of building wall defects collected via UAV imagery. The dataset is designed for object detection and classification tasks in the field of intelligent building inspection. It includes a wide range of structural types and defect categories, making it suitable for generalization across various real-world scenarios.

- **Total images**: 14,471
- **Image resolution**: High-resolution UAV photos
- **Defect types (5)**:
  - Crack
  - Leakage
  - Abscission
  - Corrosion
  - Bulge

- **Building structure types (6)**:
  - Steel structure
  - Wooden structure
  - Masonry structure
  - Brick and wood structure
  - Brick concrete structure
  - Reinforced concrete structure

- **Annotation format**: VOC XML
- **Compression format**: `.zip`

---

## 📁 Folder Structure
MBDD2025/
├── JPEGImages/ # Original UAV images
├── Annotations/ # VOC XML annotation files
├── Labels/ # Optional class label file (if available)
└── README.md # This file

---

## 🧾 Annotation Format

- Annotation files are in **PASCAL VOC XML** format.
- Each XML file corresponds to an image and contains:
  - Bounding boxes
  - Object class labels (defects only)
  - Image size and metadata

---

## 🚀 Usage

This dataset can be used to train object detection models such as:

- [Faster R-CNN](https://arxiv.org/abs/1506.01497)
- [YOLOv5/YOLOv8](https://github.com/ultralytics/yolov5)

### Steps:

1. Download and unzip the dataset:

unzip MBDD2025.zip
cd MBDD2025

2. Use tools like [MMDetection](https://github.com/open-mmlab/mmdetection) or Ultralytics YOLO to train on the VOC format.

3. Make sure to convert labels if needed (e.g., to COCO or YOLO format).

---

## 📜 License

This dataset is released under the **Creative Commons Attribution 4.0 International License (CC BY 4.0)**.
You are free to use, share, and adapt the dataset, provided appropriate credit is given.

---

## 📣 Citation

If you use **MBDD2025** in your research, please cite the dataset as follows:

@misc{MBDD2025,
title = {MBDD2025: A Deep Learning-Oriented Dataset for Diverse Building Defect Detection from UAV Images},
author = {Qikai Zha,Yiming Yao,Wenkang Zhang,Wanqi Ma},
year = {2025},
publisher = {Zenodo},
doi = {https://doi.org/10.5281/zenodo.15622584}
}

> 📌 *Replace `Your Name(s)` and `DOI` with the actual author(s) and DOI once the dataset is published on Zenodo.*

---

## 💬 Contact

If you have any questions or suggestions, feel free to open an issue or contact the dataset maintainer.

In [ ]:
import zipfile
archive_path = "/content/MBDD2025.zip"

with zipfile.ZipFile(archive_path, "r") as f:
  label_files = [i for i in f.infolist() if i.filename.startswith("MBDD2025/Labels/") and not i.is_dir()]
  print("Number of files in labels = ", len(label_files))

  for i in label_files[:40]:
    print(f"{i.filename} | {i.file_size:,} bytes")

  for i in label_files:
    if i.file_size<=100_000:
      if i.filename.lower().endswith((".txt", ".csv", ".json", ".yaml", ".yml")):
        print(f"\n--- {i.filename} ---")
        print(f.read(i.filename).decode("utf-8", errors="replace")[:5000])

  if not label_files:
    print("\nNo files found inside the Labels/ directory.")

Streaming output truncated to the last 5000 lines.

--- MBDD2025/Labels/Hefei9422.txt ---
2 0.5 0.7082291666666666 1.0 0.17668055555555554
2 0.5810195312499999 0.10992361111111112 0.17646093750000003 0.21379166666666669


--- MBDD2025/Labels/Hefei9423.txt ---
2 0.54507421875 0.09947222222222223 0.14116406249999996 0.1742777777777778
2 0.49925390625 0.7162638888888889 0.9985078125 0.2248611111111111


--- MBDD2025/Labels/Hefei9424.txt ---
2 0.536578125 0.09330555555555557 0.14770312500000005 0.18661111111111114
2 0.487984375 0.7376180555555556 0.97596875 0.2081527777777778


--- MBDD2025/Labels/Hefei9425.txt ---
2 0.5 0.7202777777777777 1.0 0.2891111111111111
2 0.5248125 0.09714583333333333 0.15815625000000005 0.19287500000000002


--- MBDD2025/Labels/Hefei9426.txt ---
2 0.5 0.6855833333333333 1.0 0.2544166666666668
2 0.5104335937500001 0.09446527777777779 0.16600781250000002 0.18893055555555557


--- MBDD2025/Labels/Hefei9427.txt ---
2 0.5 0.6855833333333333 1.0 0.2544166666666668
2 0.4986679687500001 0.08901388888888889 0.1503203125 0.16266666666666668


--- MBDD2025/Labels/Hefei9428.txt ---
2 0.5 0.7173819444444445 1.0 0.22551388888888899
2 0.4967070312500001 0.10528472222222224 0.13855468750000002 0.1580138888888889


--- MBDD2025/Labels/Hefei9429.txt ---
2 0.5 0.7289444444444445 1.0 0.2139444444444445
2 0.47318359374999996 0.10295833333333335 0.13855468750000002 0.19519444444444445


--- MBDD2025/Labels/Hefei943.txt ---
1 0.22732031250000004 0.24815277777777778 0.052000000000000005 0.49630555555555556
1 0.297375 0.35122916666666665 0.062109375 0.26448611111111114
1 0.3125390625 0.7800625 0.09821875000000002 0.40315277777777775
1 0.22515234375 0.7892430555555556 0.07366406249999997 0.4215138888888889
1 0.5653125 0.7723541666666668 0.069328125 0.4545138888888889
1 0.6584765625000001 0.5 0.06500000000000004 1.0


--- MBDD2025/Labels/Hefei9430.txt ---
2 0.46468359375 0.09795138888888891 0.11894531250000001 0.19590277777777781
2 0.5033593749999999 0.7202708333333334 0.9932812500000001 0.27754166666666663


--- MBDD2025/Labels/Hefei9431.txt ---
2 0.4653359375 0.09946527777777779 0.14378124999999997 0.19287500000000002
2 0.500109375 0.6855763888888889 0.9997812500000001 0.16190277777777778


--- MBDD2025/Labels/Hefei9432.txt ---
2 0.444421875 0.10063194444444444 0.151625 0.18590277777777778
2 0.5 0.7260555555555556 1.0 0.2659722222222222


--- MBDD2025/Labels/Hefei9433.txt ---
2 0.42743359375 0.09133333333333335 0.13332031250000004 0.15336111111111111
2 0.5 0.6855763888888889 1.0 0.23129166666666665


--- MBDD2025/Labels/Hefei9434.txt ---
2 0.5 0.7058194444444444 1.0 0.2601944444444445
2 0.42351171875000004 0.10411805555555555 0.14900781250000003 0.20681944444444444


--- MBDD2025/Labels/Hefei9435.txt ---
2 0.500109375 0.7058194444444444 0.9997812500000001 0.1676944444444444
2 0.41567187499999997 0.1064375 0.18560937500000005 0.1975138888888889
2 0.6607539062500001 0.1014375 0.30455468750000003 0.202875


--- MBDD2025/Labels/Hefei9436.txt ---
2 0.38430078125 0.09017361111111111 0.19867968749999998 0.15568055555555557
2 0.49692968750000005 0.7087083333333334 0.9938593750000001 0.18502777777777774
2 0.6548710937500002 0.10644444444444445 0.30063281250000007 0.18822222222222224


--- MBDD2025/Labels/Hefei9437.txt ---
2 0.5 0.752076388888889 1.0 0.1908194444444445
2 0.38168359375 0.09795138888888891 0.16992968749999995 0.19590277777777781
2 0.6365703125 0.1145763888888889 0.30325 0.1812638888888889


--- MBDD2025/Labels/Hefei9438.txt ---
2 0.5 0.7202708333333334 1.0 0.16190277777777778
2 0.36142578125 0.10063194444444444 0.2026015625 0.18126388888888892
2 0.6306875000000001 0.10760416666666667 0.30456250000000007 0.21379166666666669


--- MBDD2025/Labels/Hefei9439.txt ---
2 0.5 0.7087152777777778 1.0 0.1619027777777777
2 0.63134375 0.11805555555555557 0.32939062500000005 0.17427777777777778
2 0.36338281250000004 0.09563194444444445 0.15946875000000005 0.1912638888888889


--- MBDD2025/Labels/Hefei944.txt ---
1 0.65919921875 0.49659722222222225 0.08319531250000001 0.9931944444444445
1 0.56521875 0.7013333333333334 0.07723437500000002 0.49930555555555567
1 0.34557421875 0.7286180555555556 0.0854609375 0.28031944444444445
1 0.2920078125 0.3338125 0.04573437500000002 0.29956944444444444
1 0.22701171875 0.25143055555555555 0.055367187500000005 0.5028611111111111
1 0.23846093750000003 0.7692708333333333 0.05895312499999999 0.3873194444444444


--- MBDD2025/Labels/Hefei9440.txt ---
2 0.33855078125000004 0.10295833333333335 0.18299218750000001 0.19519444444444445
2 0.6012773437500001 0.10179861111111112 0.3267734375 0.19287499999999996
2 0.50661328125 0.6971458333333332 0.9867734375 0.18504166666666663


--- MBDD2025/Labels/Hefei9441.txt ---
2 0.61042578125 0.10528472222222224 0.33200781250000005 0.17195833333333335
2 0.49286328125 0.7376180555555556 0.9857265625 0.19659722222222226
2 0.346390625 0.10063194444444444 0.19084374999999998 0.19520833333333332


--- MBDD2025/Labels/Hefei9442.txt ---
2 0.34246875000000004 0.10411805555555556 0.1673125000000001 0.16498611111111114
2 0.5953984375 0.09481944444444446 0.317625 0.18358333333333335
2 0.5 0.7462916666666668 1.0 0.2139444444444445


--- MBDD2025/Labels/Hefei9443.txt ---
2 0.34377734375 0.1029513888888889 0.1699296875 0.1859027777777778
2 0.5 0.6971458333333334 1.0 0.2081527777777778
2 0.5947421875 0.12038194444444446 0.31370312499999997 0.16962500000000003


--- MBDD2025/Labels/Hefei9444.txt ---
2 0.58820703125 0.1250277777777778 0.33985156250000004 0.14175000000000001
2 0.3222109375 0.1110902777777778 0.18168750000000006 0.16962500000000003
2 0.5 0.7029305555555556 1.0 0.2197222222222223


--- MBDD2025/Labels/Hefei9445.txt ---
2 0.31763671875 0.09947222222222223 0.1803828125 0.1742777777777778
2 0.5 0.7116041666666667 1.0 0.19081944444444435
2 0.57905859375 0.10760416666666667 0.3267734375000001 0.1812638888888889


--- MBDD2025/Labels/Hefei9446.txt ---
2 0.5744843749999999 0.09679166666666666 0.291484375 0.19358333333333333
2 0.32155859375000007 0.10179861111111112 0.18299218750000001 0.1789305555555556
2 0.5 0.7116041666666667 1.0 0.20237500000000005


--- MBDD2025/Labels/Hefei9447.txt ---
2 0.57121484375 0.10179861111111112 0.3058671875 0.19287499999999996
2 0.31763281250000003 0.09598611111111112 0.14378124999999997 0.16730555555555557
2 0.5 0.7202777777777778 1.0 0.18502777777777782


--- MBDD2025/Labels/Hefei9448.txt ---
2 0.5 0.7318402777777777 1.0 0.18504166666666663
2 0.5529140625000001 0.09830555555555556 0.31109375000000006 0.18125
2 0.30456640625000003 0.10876388888888888 0.15685156250000004 0.19752777777777777


--- MBDD2025/Labels/Hefei9449.txt ---
2 0.31371484375 0.09133333333333332 0.15685156249999999 0.16730555555555554
2 0.5686015624999999 0.09714583333333335 0.3267812500000001 0.1789305555555556
2 0.49774218750000004 0.7260555555555556 0.9954843750000001 0.17347222222222228


--- MBDD2025/Labels/Hefei945.txt ---
1 0.23362890625000002 0.8045833333333333 0.0710234375 0.37661111111111106
1 0.32751562500000003 0.7906736111111111 0.058984375000000006 0.3359583333333334
1 0.29682421875000004 0.34879166666666667 0.05777343750000004 0.2781944444444444
1 0.23410937499999998 0.24211805555555554 0.044781249999999995 0.4842361111111111
1 0.6618007812500001 0.5 0.04766406249999999 1.0
1 0.5628554687499999 0.6914652777777778 0.060664062499999984 0.5187083333333334


--- MBDD2025/Labels/Hefei9450.txt ---
2 0.29802734375 0.10259722222222223 0.18822656250000003 0.20519444444444446
2 0.5 0.7405069444444444 1.0 0.20237499999999997
2 0.5914765624999999 0.10876388888888888 0.367296875 0.19752777777777777


--- MBDD2025/Labels/Hefei9451.txt ---
2 0.29607031250000004 0.10760416666666667 0.16599999999999998 0.1998472222222222
2 0.5 0.7202708333333334 1.0 0.27754166666666663
2 0.5496445312500001 0.12503472222222223 0.30455468750000003 0.17893055555555554


--- MBDD2025/Labels/Hefei9452.txt ---
2 0.5 0.7029236111111111 1.0 0.19659722222222226
2 0.5646796875 0.14013194444444443 0.32939062500000005 0.14406944444444444
2 0.2993359375 0.10063194444444444 0.162078125 0.19520833333333332


--- MBDD2025/Labels/Hefei9453.txt ---
2 0.5 0.733125 1.0 0.20880555555555552
2 0.29280078125 0.5375763888888889 0.23963281250000001 0.17815277777777777


--- MBDD2025/Labels/Hefei9454.txt ---
2 0.26448046875000003 0.5424166666666667 0.17863281250000002 0.16461111111111118
2 0.51650390625 0.7030069444444444 0.9486484375 0.2449305555555556


--- MBDD2025/Labels/Hefei9455.txt ---
2 0.5 0.7308819444444445 1.0 0.1590138888888889
2 0.28462890625 0.5443541666666667 0.19497656250000003 0.1839583333333334


--- MBDD2025/Labels/Hefei9456.txt ---
2 0.27646484375 0.5530694444444445 0.23310156250000003 0.17041666666666666
2 0.50539453125 0.7188333333333333 0.9892109375000001 0.18311111111111117


--- MBDD2025/Labels/Hefei9457.txt ---
2 0.5 0.7718333333333334 1.0 0.2891111111111111
2 0.26937890625 0.5395069444444445 0.1797265625 0.15879166666666672


--- MBDD2025/Labels/Hefei9458.txt ---
2 0.5081054687500001 0.6995555555555557 0.9837890625000001 0.1541944444444445
2 0.26230078125 0.5559722222222222 0.17863281250000002 0.16847222222222225


--- MBDD2025/Labels/Hefei9459.txt ---
2 0.5026835937499999 0.7381041666666667 0.9946328125000001 0.17345833333333333
2 0.27265234375 0.566625 0.1644765625 0.1626666666666666


--- MBDD2025/Labels/Hefei946.txt ---
1 0.6632421875000001 0.5 0.053437499999999985 1.0
1 0.56863671875 0.7209930555555556 0.060664062499999984 0.4853194444444445
1 0.34330859375 0.7802569444444444 0.08088281249999998 0.43948611111111113
1 0.29852734375 0.3242638888888889 0.037554687499999996 0.32355555555555554
1 0.22631249999999997 0.23788194444444447 0.052000000000000005 0.47576388888888893
1 0.237140625 0.7853888888888889 0.06499999999999999 0.4292222222222223


--- MBDD2025/Labels/Hefei9460.txt ---
2 0.27156250000000004 0.5191805555555555 0.15140625000000002 0.1839722222222223
2 0.49462500000000004 0.7212361111111111 0.9892500000000001 0.21683333333333335


--- MBDD2025/Labels/Hefei9461.txt ---
2 0.5 0.7164236111111112 1.0 0.2842916666666666
2 0.278640625 0.5288611111111111 0.15031250000000004 0.1529722222222223


--- MBDD2025/Labels/Hefei9462.txt ---
2 0.5 0.7091875000000001 1.0 0.23129166666666665


--- MBDD2025/Labels/Hefei9463.txt ---
2 0.41174609375 0.10455555555555555 0.6496328125 0.17422222222222222
2 0.49415625 0.7010902777777779 0.9883125 0.17893055555555562


--- MBDD2025/Labels/Hefei9464.txt ---
2 0.49489062500000003 0.7022083333333334 0.9897812500000001 0.1806944444444444
2 0.40455859375000003 0.09551388888888891 0.6274140625000001 0.18125


--- MBDD2025/Labels/Hefei9465.txt ---
2 0.5 0.6914930555555556 1.0 0.29112499999999997
2 0.38952734375000003 0.09772222222222222 0.6470234375000001 0.19544444444444445


--- MBDD2025/Labels/Hefei9466.txt ---
2 0.5 0.7400208333333335 1.0 0.2141527777777777
2 0.39998437499999995 0.09888194444444444 0.610421875 0.19776388888888888


--- MBDD2025/Labels/Hefei9467.txt ---
2 0.5011757812500001 0.7165902777777778 0.9976484375000001 0.2208472222222223
2 0.3941015625 0.11165972222222222 0.62740625 0.22331944444444443


--- MBDD2025/Labels/Hefei9468.txt ---
2 0.39198046875000003 0.1045763888888889 0.6474921875 0.19073611111111113
2 0.5 0.7383402777777778 1.0 0.21748611111111107


--- MBDD2025/Labels/Hefei9469.txt ---
2 0.5011757812500001 0.711576388888889 0.9976484375000001 0.2442638888888889
2 0.40138671875 0.10625 0.6361953125 0.19408333333333336


--- MBDD2025/Labels/Hefei947.txt ---
1 0.22703125000000002 0.7866736111111111 0.07078124999999998 0.42665277777777777
1 0.32019531250000005 0.7674166666666666 0.0924375 0.46516666666666673
1 0.30430859375 0.3627847222222222 0.037554687499999996 0.2875972222222223
1 0.22992187500000003 0.25200694444444444 0.05632812500000002 0.5040138888888889
1 0.6603554687500001 0.4972361111111111 0.07077343749999994 0.9944722222222222
1 0.56574609375 0.7261319444444445 0.06644531249999996 0.5418194444444445


--- MBDD2025/Labels/Hefei9470.txt ---
2 0.38256640625000005 0.09160416666666667 0.6361953125 0.18320833333333333
2 0.5 0.7065555555555556 1.0 0.21416666666666673


--- MBDD2025/Labels/Hefei9471.txt ---
2 0.37409765625 0.09997222222222223 0.5853828125 0.19994444444444445
2 0.5 0.7032083333333333 1.0 0.20747222222222222


--- MBDD2025/Labels/Hefei9472.txt ---
2 0.5 0.7082291666666667 1.0 0.19743055555555553
2 0.38256640625000005 0.09829861111111113 0.5910234375 0.19659722222222226


--- MBDD2025/Labels/Hefei9473.txt ---
2 0.49244140625000005 0.6814583333333333 0.9848828125000001 0.19741666666666674
2 0.37488671875 0.09529166666666666 0.6443984375 0.17427777777777778


--- MBDD2025/Labels/Hefei9474.txt ---
2 0.3951484375 0.09877777777777778 0.63003125 0.18125
2 0.5 0.7232847222222222 1.0 0.20745833333333344


--- MBDD2025/Labels/Hefei9475.txt ---
2 0.5 0.6814583333333333 1.0 0.23088888888888892
2 0.37357812500000004 0.0964513888888889 0.6025781250000001 0.17659722222222224


--- MBDD2025/Labels/Hefei9476.txt ---
2 0.38469140625000003 0.10342361111111112 0.6012734375000001 0.19054166666666666
2 0.5058828125 0.7048819444444444 0.9882343750000001 0.23087500000000002


--- MBDD2025/Labels/Hefei9477.txt ---
2 0.5 0.6931736111111112 1.0 0.2208472222222223
2 0.37358203125 0.09761111111111112 0.5895078125000001 0.17427777777777778


--- MBDD2025/Labels/Hefei9478.txt ---
2 0.38972265625 0.10197916666666666 0.6361953124999999 0.20395833333333332
2 0.5 0.7366736111111111 1.0 0.24093055555555554


--- MBDD2025/Labels/Hefei9479.txt ---
2 0.36337109375000004 0.09695833333333334 0.5985546875000001 0.19391666666666668
2 0.5 0.7316527777777777 1.0 0.3178888888888889


--- MBDD2025/Labels/Hefei948.txt ---
1 0.569359375 0.7314652777777778 0.06500000000000004 0.5370694444444445
1 0.66830078125 0.5 0.05777343749999995 1.0
1 0.30358593750000007 0.35507638888888887 0.03321875000000003 0.2824583333333333
1 0.22992187500000003 0.25200694444444444 0.06789062500000001 0.5040138888888889
1 0.236421875 0.7813402777777779 0.052000000000000005 0.43654166666666666
1 0.32525390625 0.8046458333333334 0.07655468750000001 0.3907083333333333


--- MBDD2025/Labels/Hefei9480.txt ---
2 0.5 0.7065555555555556 1.0 0.24761111111111117
2 0.369015625 0.10532638888888889 0.60984375 0.21065277777777777


--- MBDD2025/Labels/Hefei9481.txt ---
2 0.37371875000000004 0.096875 0.64184375 0.1873888888888889
2 0.5 0.7216111111111112 1.0 0.2576666666666667


--- MBDD2025/Labels/Hefei9482.txt ---
2 0.33701953125 0.09528472222222223 0.5910234375 0.19056944444444446
2 0.5 0.7182777777777779 1.0 0.2376111111111112


--- MBDD2025/Labels/Hefei9483.txt ---
2 0.49991796875 0.6986875 0.9998359375 0.17620833333333336
2 0.33083984375 0.09403472222222223 0.6274140625000001 0.1617361111111111


--- MBDD2025/Labels/Hefei9484.txt ---
2 0.5 0.7110833333333334 1.0 0.22849999999999998
2 0.33789843750000004 0.1051875 0.588203125 0.20634722222222227


--- MBDD2025/Labels/Hefei9485.txt ---
2 0.5 0.6950138888888888 1.0 0.18977777777777785
2 0.34103515625 0.09302777777777779 0.6038828125000001 0.18605555555555559


--- MBDD2025/Labels/Hefei9486.txt ---
2 0.5 0.6979166666666667 1.0 0.21494444444444444
2 0.31593750000000004 0.09581250000000001 0.581921875 0.19162500000000002


--- MBDD2025/Labels/Hefei9487.txt ---
2 0.31828906250000005 0.09263888888888888 0.596046875 0.18125
2 0.5 0.6892013888888889 1.0 0.17815277777777783


--- MBDD2025/Labels/Hefei9488.txt ---
2 0.5 0.6950069444444444 1.0 0.19751388888888888
2 0.30344921875 0.11215972222222224 0.6068984375 0.19240277777777778


--- MBDD2025/Labels/Hefei9489.txt ---
2 0.29246875 0.10797916666666665 0.5849375 0.21193055555555557
2 0.5 0.7055555555555556 1.0 0.1806944444444444


--- MBDD2025/Labels/Hefei949.txt ---
1 0.33175390625 0.8057361111111111 0.08377343750000002 0.3826111111111111
1 0.30647265625 0.39231250000000006 0.03033593749999999 0.3004305555555556
1 0.22775390625 0.24815277777777778 0.0664453125 0.49630555555555556
1 0.23786718750000002 0.782625 0.052000000000000005 0.4031388888888889
1 0.576578125 0.7531041666666667 0.07943750000000005 0.4673194444444445
1 0.667578125 0.5 0.04189062499999992 1.0


--- MBDD2025/Labels/Hefei9490.txt ---
2 0.2940390625 0.10278472222222222 0.588078125 0.20556944444444444
2 0.5 0.7099027777777778 1.0 0.20411111111111116


--- MBDD2025/Labels/Hefei9491.txt ---
2 0.5 0.7182638888888889 1.0 0.2074722222222223
2 0.30260546875 0.09264583333333333 0.5834921875 0.17009722222222223


--- MBDD2025/Labels/Hefei9492.txt ---
2 0.312015625 0.09302777777777779 0.6023125 0.18605555555555559
2 0.5 0.7232916666666667 1.0 0.23088888888888892


--- MBDD2025/Labels/Hefei9493.txt ---
2 0.28612890625000004 0.09295833333333335 0.5722578125000001 0.1859166666666667
2 0.5 0.6985972222222223 1.0 0.21683333333333327


--- MBDD2025/Labels/Hefei9494.txt ---
2 0.28090234375 0.10341666666666666 0.5618046875 0.2068333333333333
2 0.5069765625 0.7226875 0.9860468750000001 0.17668055555555562


--- MBDD2025/Labels/Hefei9495.txt ---
2 0.5 0.6905625000000001 1.0 0.2650138888888889
2 0.28861718750000004 0.09179166666666667 0.5672812500000001 0.18358333333333335


--- MBDD2025/Labels/Hefei9496.txt ---
2 0.283515625 0.09993055555555556 0.56703125 0.19519444444444445
2 0.5 0.7154166666666667 1.0 0.21511111111111103


--- MBDD2025/Labels/Hefei9497.txt ---
2 0.27959375000000003 0.10806250000000002 0.5591875000000001 0.21145833333333333
2 0.5 0.7015416666666667 1.0 0.24286111111111106


--- MBDD2025/Labels/Hefei9498.txt ---
2 0.2665234375 0.08947222222222223 0.533046875 0.17894444444444446
2 0.5 0.7119444444444445 1.0 0.20816666666666658


--- MBDD2025/Labels/Hefei9499.txt ---
2 0.5 0.6841875000000001 1.0 0.24979166666666663
2 0.27305859375 0.0906388888888889 0.5461171875 0.1766111111111111


--- MBDD2025/Labels/Hefei95.txt ---
3 0.056746093750000004 0.32586111111111116 0.0393359375 0.16944444444444445
3 0.17626171875000002 0.38167361111111114 0.09530468750000001 0.07395833333333333
3 0.28708203125000004 0.3056875 0.024960937499999992 0.06993055555555559
3 0.57185546875 0.3277083333333333 0.03319531250000001 0.057722222222222265
3 0.6347773437500001 0.3692083333333334 0.024804687500000002 0.05772222222222223


--- MBDD2025/Labels/Hefei950.txt ---
1 0.6740742187500001 0.49852083333333336 0.06355468750000003 0.9970416666666667
1 0.57730078125 0.7556666666666667 0.07222656249999995 0.48275
1 0.33680859375000005 0.8226249999999999 0.0794453125 0.35475
1 0.30936328125 0.38975000000000004 0.0592265625 0.27988888888888885
1 0.24003125000000003 0.28025694444444443 0.062109375 0.5605138888888889
1 0.24436328124999998 0.787763888888889 0.04766406250000004 0.38774999999999993


--- MBDD2025/Labels/Hefei9500.txt ---
2 0.26391015625 0.09760416666666667 0.5278203125 0.19520833333333334
2 0.5 0.7188819444444445 1.0 0.24979166666666663


--- MBDD2025/Labels/Hefei9501.txt ---
2 0.275671875 0.08714583333333334 0.55134375 0.17429166666666668
2 0.5 0.6945972222222223 1.0 0.29836111111111113


--- MBDD2025/Labels/Hefei9502.txt ---
2 0.25724609375 0.0790138888888889 0.5097734375 0.1580277777777778
2 0.49901171875000006 0.7119444444444445 0.9980234375000001 0.26366666666666666


--- MBDD2025/Labels/Hefei9503.txt ---
2 0.51990234375 0.732763888888889 0.9484296875 0.2220277777777777
2 0.26992187500000003 0.09528472222222223 0.48885937500000004 0.1789305555555556


--- MBDD2025/Labels/Hefei9504.txt ---
2 0.5 0.7154166666666666 1.0 0.1595833333333333
2 0.271625 0.09296527777777779 0.47056250000000005 0.16731944444444444


--- MBDD2025/Labels/Hefei9505.txt ---
2 0.2729296875 0.09064583333333334 0.48885937500000004 0.17195833333333335
2 0.5 0.7223541666666667 1.0 0.1457083333333333


--- MBDD2025/Labels/Hefei9506.txt ---
2 0.503328125 0.7223611111111111 0.9933437500000001 0.20122222222222214
2 0.26705078125 0.09993055555555555 0.4823203125 0.18125


--- MBDD2025/Labels/Hefei9507.txt ---
2 0.244828125 0.09645138888888888 0.4770937500000001 0.19287500000000002
2 0.5 0.7154166666666666 1.0 0.1734722222222222


--- MBDD2025/Labels/Hefei9508.txt ---

In [ ]:
from pathlib import Path

archive_path = Path("/content/MBDD2025.zip")

if archive_path.exists():
    size_gb = archive_path.stat().st_size / (1024**3)
    print(f"Partial or complete download: {size_gb:.2f} GiB")
    print(f"Size in bytes: {archive_path.stat().st_size:,}")
else:
    print("No downloaded archive found.")

Partial or complete download: 1.83 GiB
Size in bytes: 1,970,274,304

In [ ]:
import requests

url = (
    "https://zenodo.org/api/records/15622584/"
    "files/MBDD2025.zip/content"
)

response = requests.get(url, headers={"Range": "bytes=1970274304-1970274304"}, stream=True, timeout=30)

print("HTTP status:", response.status_code)
print("Content-Range:", response.headers.get("Content-Range"))
print("Accept-Ranges:", response.headers.get("Accept-Ranges"))

response.close()

HTTP status: 206
Content-Range: bytes 1970274304-1970274304/2533687033
Accept-Ranges: bytes

In [ ]:
import requests
from pathlib import Path

url = (
    "https://zenodo.org/api/records/15622584/"
    "files/MBDD2025.zip/content"
)

path = Path("/content/MBDD2025.zip")
expected_size = 2533687033

start = path.stat().st_size

if start == expected_size:
    print("Archive is already complete!")

elif start > expected_size:
    raise RuntimeError("File is larger than expected. Stopping.")

else:
    headers = {"Range": f"bytes={start}-"}
    with requests.get(url, headers=headers, stream=True, timeout=(30, 120)) as response:
        content_range = response.headers.get("Content-Range", "")
        expected_prefix = f"bytes {start}-"

        if response.status_code != 206:
            raise RuntimeError(f"Expected HTTP 206, got {response.status_code}. Existing file was not modified.")

        if not content_range.startswith(expected_prefix):
            raise RuntimeError(f"Unexpected Content-Range: {content_range}. Existing file was not modified.")

        print("Resuming from:", f"{start:,}", "bytes")
        with path.open("ab") as f:
            for i in response.iter_content(chunk_size=1024*1024):
                if i:
                    f.write(i)
                    start = start+len(i)
                    if start % (100*1024*1024) < len(i):
                        print(f"Downloaded: {start / 1024**3:.2f} GiB")

    actual_size = path.stat().st_size
    print(f"\nFinal size: {actual_size:,} bytes")

    if actual_size == expected_size:
        print("SUCCESS: Archive size verified!")
    else:
        print("Download incomplete. Rerun this cell to resume.")

Resuming from: 1,970,274,304 bytes
Downloaded: 1.86 GiB
Downloaded: 1.95 GiB
Downloaded: 2.05 GiB
Downloaded: 2.15 GiB
Downloaded: 2.25 GiB
Downloaded: 2.34 GiB

Final size: 2,533,687,033 bytes
SUCCESS: Archive size verified!

In [ ]:
# Verifying the ZIP integrity
import zipfile

path = "/content/MBDD2025.zip"

with zipfile.ZipFile(path, "r") as f:
  badFile = f.testzip()

if badFile is None:
  print("ZIP integrity verified. Ready to continue!")
else:
  print("Corrupted archive member: ", badFile)

ZIP integrity verified. Ready to continue!

In [ ]:
# Finding the class mapping
with zipfile.ZipFile(archive_path, "r") as f:
  for i in f.namelist():
    lower = i.lower()
    if (i.startswith("MBDD2025/") and not i.endswith("/") and any(j in lower for j in ("classes.txt", "class_names", "data.yaml", "dataset.yaml", "labels.txt", "metadata"))):
      print("\nFILE: ", i)
      info = f.getinfo(i)

      if info.file_size <= 20000:
        print(f.read(i).decode("utf-8", errors="replace"))
      else:
        print("File too large to preview.")

In [ ]:
import zipfile

archive_path = "/content/MBDD2025.zip"
with zipfile.ZipFile(archive_path, "r") as f:
    names = f.namelist()
    matches = [i for i in names if any(j in j.lower() for j in [
            "classes.txt",
            "class_names",
            "data.yaml",
            "dataset.yaml",
            "labels.txt",
            "metadata"
        ]) and not j.endswith("/")
    ]

    if matches:
        print("Possible class-mapping files found:")
        for i in matches:
            print("\nFILE:", i)
            if f.getinfo(i).file_size <= 20000:
                print(f.read(i).decode("utf-8", errors="replace"))
    else:
        print("No obvious class-mapping files found.")
        print("Next, we will inspect the numeric class IDs.")

Streaming output truncated to the last 5000 lines.
2 0.6306875000000001 0.10760416666666667 0.30456250000000007 0.21379166666666669


FILE: MBDD2025/Labels/Hefei9439.txt
2 0.5 0.7087152777777778 1.0 0.1619027777777777
2 0.63134375 0.11805555555555557 0.32939062500000005 0.17427777777777778
2 0.36338281250000004 0.09563194444444445 0.15946875000000005 0.1912638888888889


FILE: MBDD2025/Labels/Hefei944.txt
1 0.65919921875 0.49659722222222225 0.08319531250000001 0.9931944444444445
1 0.56521875 0.7013333333333334 0.07723437500000002 0.49930555555555567
1 0.34557421875 0.7286180555555556 0.0854609375 0.28031944444444445
1 0.2920078125 0.3338125 0.04573437500000002 0.29956944444444444
1 0.22701171875 0.25143055555555555 0.055367187500000005 0.5028611111111111
1 0.23846093750000003 0.7692708333333333 0.05895312499999999 0.3873194444444444


FILE: MBDD2025/Labels/Hefei9440.txt
2 0.33855078125000004 0.10295833333333335 0.18299218750000001 0.19519444444444445
2 0.6012773437500001 0.10179861111111112 0.3267734375 0.19287499999999996
2 0.50661328125 0.6971458333333332 0.9867734375 0.18504166666666663


FILE: MBDD2025/Labels/Hefei9441.txt
2 0.61042578125 0.10528472222222224 0.33200781250000005 0.17195833333333335
2 0.49286328125 0.7376180555555556 0.9857265625 0.19659722222222226
2 0.346390625 0.10063194444444444 0.19084374999999998 0.19520833333333332


FILE: MBDD2025/Labels/Hefei9442.txt
2 0.34246875000000004 0.10411805555555556 0.1673125000000001 0.16498611111111114
2 0.5953984375 0.09481944444444446 0.317625 0.18358333333333335
2 0.5 0.7462916666666668 1.0 0.2139444444444445


FILE: MBDD2025/Labels/Hefei9443.txt
2 0.34377734375 0.1029513888888889 0.1699296875 0.1859027777777778
2 0.5 0.6971458333333334 1.0 0.2081527777777778
2 0.5947421875 0.12038194444444446 0.31370312499999997 0.16962500000000003


FILE: MBDD2025/Labels/Hefei9444.txt
2 0.58820703125 0.1250277777777778 0.33985156250000004 0.14175000000000001
2 0.3222109375 0.1110902777777778 0.18168750000000006 0.16962500000000003
2 0.5 0.7029305555555556 1.0 0.2197222222222223


FILE: MBDD2025/Labels/Hefei9445.txt
2 0.31763671875 0.09947222222222223 0.1803828125 0.1742777777777778
2 0.5 0.7116041666666667 1.0 0.19081944444444435
2 0.57905859375 0.10760416666666667 0.3267734375000001 0.1812638888888889


FILE: MBDD2025/Labels/Hefei9446.txt
2 0.5744843749999999 0.09679166666666666 0.291484375 0.19358333333333333
2 0.32155859375000007 0.10179861111111112 0.18299218750000001 0.1789305555555556
2 0.5 0.7116041666666667 1.0 0.20237500000000005


FILE: MBDD2025/Labels/Hefei9447.txt
2 0.57121484375 0.10179861111111112 0.3058671875 0.19287499999999996
2 0.31763281250000003 0.09598611111111112 0.14378124999999997 0.16730555555555557
2 0.5 0.7202777777777778 1.0 0.18502777777777782


FILE: MBDD2025/Labels/Hefei9448.txt
2 0.5 0.7318402777777777 1.0 0.18504166666666663
2 0.5529140625000001 0.09830555555555556 0.31109375000000006 0.18125
2 0.30456640625000003 0.10876388888888888 0.15685156250000004 0.19752777777777777


FILE: MBDD2025/Labels/Hefei9449.txt
2 0.31371484375 0.09133333333333332 0.15685156249999999 0.16730555555555554
2 0.5686015624999999 0.09714583333333335 0.3267812500000001 0.1789305555555556
2 0.49774218750000004 0.7260555555555556 0.9954843750000001 0.17347222222222228


FILE: MBDD2025/Labels/Hefei945.txt
1 0.23362890625000002 0.8045833333333333 0.0710234375 0.37661111111111106
1 0.32751562500000003 0.7906736111111111 0.058984375000000006 0.3359583333333334
1 0.29682421875000004 0.34879166666666667 0.05777343750000004 0.2781944444444444
1 0.23410937499999998 0.24211805555555554 0.044781249999999995 0.4842361111111111
1 0.6618007812500001 0.5 0.04766406249999999 1.0
1 0.5628554687499999 0.6914652777777778 0.060664062499999984 0.5187083333333334


FILE: MBDD2025/Labels/Hefei9450.txt
2 0.29802734375 0.10259722222222223 0.18822656250000003 0.20519444444444446
2 0.5 0.7405069444444444 1.0 0.20237499999999997
2 0.5914765624999999 0.10876388888888888 0.367296875 0.19752777777777777


FILE: MBDD2025/Labels/Hefei9451.txt
2 0.29607031250000004 0.10760416666666667 0.16599999999999998 0.1998472222222222
2 0.5 0.7202708333333334 1.0 0.27754166666666663
2 0.5496445312500001 0.12503472222222223 0.30455468750000003 0.17893055555555554


FILE: MBDD2025/Labels/Hefei9452.txt
2 0.5 0.7029236111111111 1.0 0.19659722222222226
2 0.5646796875 0.14013194444444443 0.32939062500000005 0.14406944444444444
2 0.2993359375 0.10063194444444444 0.162078125 0.19520833333333332


FILE: MBDD2025/Labels/Hefei9453.txt
2 0.5 0.733125 1.0 0.20880555555555552
2 0.29280078125 0.5375763888888889 0.23963281250000001 0.17815277777777777


FILE: MBDD2025/Labels/Hefei9454.txt
2 0.26448046875000003 0.5424166666666667 0.17863281250000002 0.16461111111111118
2 0.51650390625 0.7030069444444444 0.9486484375 0.2449305555555556


FILE: MBDD2025/Labels/Hefei9455.txt
2 0.5 0.7308819444444445 1.0 0.1590138888888889
2 0.28462890625 0.5443541666666667 0.19497656250000003 0.1839583333333334


FILE: MBDD2025/Labels/Hefei9456.txt
2 0.27646484375 0.5530694444444445 0.23310156250000003 0.17041666666666666
2 0.50539453125 0.7188333333333333 0.9892109375000001 0.18311111111111117


FILE: MBDD2025/Labels/Hefei9457.txt
2 0.5 0.7718333333333334 1.0 0.2891111111111111
2 0.26937890625 0.5395069444444445 0.1797265625 0.15879166666666672


FILE: MBDD2025/Labels/Hefei9458.txt
2 0.5081054687500001 0.6995555555555557 0.9837890625000001 0.1541944444444445
2 0.26230078125 0.5559722222222222 0.17863281250000002 0.16847222222222225


FILE: MBDD2025/Labels/Hefei9459.txt
2 0.5026835937499999 0.7381041666666667 0.9946328125000001 0.17345833333333333
2 0.27265234375 0.566625 0.1644765625 0.1626666666666666


FILE: MBDD2025/Labels/Hefei946.txt
1 0.6632421875000001 0.5 0.053437499999999985 1.0
1 0.56863671875 0.7209930555555556 0.060664062499999984 0.4853194444444445
1 0.34330859375 0.7802569444444444 0.08088281249999998 0.43948611111111113
1 0.29852734375 0.3242638888888889 0.037554687499999996 0.32355555555555554
1 0.22631249999999997 0.23788194444444447 0.052000000000000005 0.47576388888888893
1 0.237140625 0.7853888888888889 0.06499999999999999 0.4292222222222223


FILE: MBDD2025/Labels/Hefei9460.txt
2 0.27156250000000004 0.5191805555555555 0.15140625000000002 0.1839722222222223
2 0.49462500000000004 0.7212361111111111 0.9892500000000001 0.21683333333333335


FILE: MBDD2025/Labels/Hefei9461.txt
2 0.5 0.7164236111111112 1.0 0.2842916666666666
2 0.278640625 0.5288611111111111 0.15031250000000004 0.1529722222222223


FILE: MBDD2025/Labels/Hefei9462.txt
2 0.5 0.7091875000000001 1.0 0.23129166666666665


FILE: MBDD2025/Labels/Hefei9463.txt
2 0.41174609375 0.10455555555555555 0.6496328125 0.17422222222222222
2 0.49415625 0.7010902777777779 0.9883125 0.17893055555555562


FILE: MBDD2025/Labels/Hefei9464.txt
2 0.49489062500000003 0.7022083333333334 0.9897812500000001 0.1806944444444444
2 0.40455859375000003 0.09551388888888891 0.6274140625000001 0.18125


FILE: MBDD2025/Labels/Hefei9465.txt
2 0.5 0.6914930555555556 1.0 0.29112499999999997
2 0.38952734375000003 0.09772222222222222 0.6470234375000001 0.19544444444444445


FILE: MBDD2025/Labels/Hefei9466.txt
2 0.5 0.7400208333333335 1.0 0.2141527777777777
2 0.39998437499999995 0.09888194444444444 0.610421875 0.19776388888888888


FILE: MBDD2025/Labels/Hefei9467.txt
2 0.5011757812500001 0.7165902777777778 0.9976484375000001 0.2208472222222223
2 0.3941015625 0.11165972222222222 0.62740625 0.22331944444444443


FILE: MBDD2025/Labels/Hefei9468.txt
2 0.39198046875000003 0.1045763888888889 0.6474921875 0.19073611111111113
2 0.5 0.7383402777777778 1.0 0.21748611111111107


FILE: MBDD2025/Labels/Hefei9469.txt
2 0.5011757812500001 0.711576388888889 0.9976484375000001 0.2442638888888889
2 0.40138671875 0.10625 0.6361953125 0.19408333333333336


FILE: MBDD2025/Labels/Hefei947.txt
1 0.22703125000000002 0.7866736111111111 0.07078124999999998 0.42665277777777777
1 0.32019531250000005 0.7674166666666666 0.0924375 0.46516666666666673
1 0.30430859375 0.3627847222222222 0.037554687499999996 0.2875972222222223
1 0.22992187500000003 0.25200694444444444 0.05632812500000002 0.5040138888888889
1 0.6603554687500001 0.4972361111111111 0.07077343749999994 0.9944722222222222
1 0.56574609375 0.7261319444444445 0.06644531249999996 0.5418194444444445


FILE: MBDD2025/Labels/Hefei9470.txt
2 0.38256640625000005 0.09160416666666667 0.6361953125 0.18320833333333333
2 0.5 0.7065555555555556 1.0 0.21416666666666673


FILE: MBDD2025/Labels/Hefei9471.txt
2 0.37409765625 0.09997222222222223 0.5853828125 0.19994444444444445
2 0.5 0.7032083333333333 1.0 0.20747222222222222


FILE: MBDD2025/Labels/Hefei9472.txt
2 0.5 0.7082291666666667 1.0 0.19743055555555553
2 0.38256640625000005 0.09829861111111113 0.5910234375 0.19659722222222226


FILE: MBDD2025/Labels/Hefei9473.txt
2 0.49244140625000005 0.6814583333333333 0.9848828125000001 0.19741666666666674
2 0.37488671875 0.09529166666666666 0.6443984375 0.17427777777777778


FILE: MBDD2025/Labels/Hefei9474.txt
2 0.3951484375 0.09877777777777778 0.63003125 0.18125
2 0.5 0.7232847222222222 1.0 0.20745833333333344


FILE: MBDD2025/Labels/Hefei9475.txt
2 0.5 0.6814583333333333 1.0 0.23088888888888892
2 0.37357812500000004 0.0964513888888889 0.6025781250000001 0.17659722222222224


FILE: MBDD2025/Labels/Hefei9476.txt
2 0.38469140625000003 0.10342361111111112 0.6012734375000001 0.19054166666666666
2 0.5058828125 0.7048819444444444 0.9882343750000001 0.23087500000000002


FILE: MBDD2025/Labels/Hefei9477.txt
2 0.5 0.6931736111111112 1.0 0.2208472222222223
2 0.37358203125 0.09761111111111112 0.5895078125000001 0.17427777777777778


FILE: MBDD2025/Labels/Hefei9478.txt
2 0.38972265625 0.10197916666666666 0.6361953124999999 0.20395833333333332
2 0.5 0.7366736111111111 1.0 0.24093055555555554


FILE: MBDD2025/Labels/Hefei9479.txt
2 0.36337109375000004 0.09695833333333334 0.5985546875000001 0.19391666666666668
2 0.5 0.7316527777777777 1.0 0.3178888888888889


FILE: MBDD2025/Labels/Hefei948.txt
1 0.569359375 0.7314652777777778 0.06500000000000004 0.5370694444444445
1 0.66830078125 0.5 0.05777343749999995 1.0
1 0.30358593750000007 0.35507638888888887 0.03321875000000003 0.2824583333333333
1 0.22992187500000003 0.25200694444444444 0.06789062500000001 0.5040138888888889
1 0.236421875 0.7813402777777779 0.052000000000000005 0.43654166666666666
1 0.32525390625 0.8046458333333334 0.07655468750000001 0.3907083333333333


FILE: MBDD2025/Labels/Hefei9480.txt
2 0.5 0.7065555555555556 1.0 0.24761111111111117
2 0.369015625 0.10532638888888889 0.60984375 0.21065277777777777


FILE: MBDD2025/Labels/Hefei9481.txt
2 0.37371875000000004 0.096875 0.64184375 0.1873888888888889
2 0.5 0.7216111111111112 1.0 0.2576666666666667


FILE: MBDD2025/Labels/Hefei9482.txt
2 0.33701953125 0.09528472222222223 0.5910234375 0.19056944444444446
2 0.5 0.7182777777777779 1.0 0.2376111111111112


FILE: MBDD2025/Labels/Hefei9483.txt
2 0.49991796875 0.6986875 0.9998359375 0.17620833333333336
2 0.33083984375 0.09403472222222223 0.6274140625000001 0.1617361111111111


FILE: MBDD2025/Labels/Hefei9484.txt
2 0.5 0.7110833333333334 1.0 0.22849999999999998
2 0.33789843750000004 0.1051875 0.588203125 0.20634722222222227


FILE: MBDD2025/Labels/Hefei9485.txt
2 0.5 0.6950138888888888 1.0 0.18977777777777785
2 0.34103515625 0.09302777777777779 0.6038828125000001 0.18605555555555559


FILE: MBDD2025/Labels/Hefei9486.txt
2 0.5 0.6979166666666667 1.0 0.21494444444444444
2 0.31593750000000004 0.09581250000000001 0.581921875 0.19162500000000002


FILE: MBDD2025/Labels/Hefei9487.txt
2 0.31828906250000005 0.09263888888888888 0.596046875 0.18125
2 0.5 0.6892013888888889 1.0 0.17815277777777783


FILE: MBDD2025/Labels/Hefei9488.txt
2 0.5 0.6950069444444444 1.0 0.19751388888888888
2 0.30344921875 0.11215972222222224 0.6068984375 0.19240277777777778


FILE: MBDD2025/Labels/Hefei9489.txt
2 0.29246875 0.10797916666666665 0.5849375 0.21193055555555557
2 0.5 0.7055555555555556 1.0 0.1806944444444444


FILE: MBDD2025/Labels/Hefei949.txt
1 0.33175390625 0.8057361111111111 0.08377343750000002 0.3826111111111111
1 0.30647265625 0.39231250000000006 0.03033593749999999 0.3004305555555556
1 0.22775390625 0.24815277777777778 0.0664453125 0.49630555555555556
1 0.23786718750000002 0.782625 0.052000000000000005 0.4031388888888889
1 0.576578125 0.7531041666666667 0.07943750000000005 0.4673194444444445
1 0.667578125 0.5 0.04189062499999992 1.0


FILE: MBDD2025/Labels/Hefei9490.txt
2 0.2940390625 0.10278472222222222 0.588078125 0.20556944444444444
2 0.5 0.7099027777777778 1.0 0.20411111111111116


FILE: MBDD2025/Labels/Hefei9491.txt
2 0.5 0.7182638888888889 1.0 0.2074722222222223
2 0.30260546875 0.09264583333333333 0.5834921875 0.17009722222222223


FILE: MBDD2025/Labels/Hefei9492.txt
2 0.312015625 0.09302777777777779 0.6023125 0.18605555555555559
2 0.5 0.7232916666666667 1.0 0.23088888888888892


FILE: MBDD2025/Labels/Hefei9493.txt
2 0.28612890625000004 0.09295833333333335 0.5722578125000001 0.1859166666666667
2 0.5 0.6985972222222223 1.0 0.21683333333333327


FILE: MBDD2025/Labels/Hefei9494.txt
2 0.28090234375 0.10341666666666666 0.5618046875 0.2068333333333333
2 0.5069765625 0.7226875 0.9860468750000001 0.17668055555555562


FILE: MBDD2025/Labels/Hefei9495.txt
2 0.5 0.6905625000000001 1.0 0.2650138888888889
2 0.28861718750000004 0.09179166666666667 0.5672812500000001 0.18358333333333335


FILE: MBDD2025/Labels/Hefei9496.txt
2 0.283515625 0.09993055555555556 0.56703125 0.19519444444444445
2 0.5 0.7154166666666667 1.0 0.21511111111111103


FILE: MBDD2025/Labels/Hefei9497.txt
2 0.27959375000000003 0.10806250000000002 0.5591875000000001 0.21145833333333333
2 0.5 0.7015416666666667 1.0 0.24286111111111106


FILE: MBDD2025/Labels/Hefei9498.txt
2 0.2665234375 0.08947222222222223 0.533046875 0.17894444444444446
2 0.5 0.7119444444444445 1.0 0.20816666666666658


FILE: MBDD2025/Labels/Hefei9499.txt
2 0.5 0.6841875000000001 1.0 0.24979166666666663
2 0.27305859375 0.0906388888888889 0.5461171875 0.1766111111111111


FILE: MBDD2025/Labels/Hefei95.txt
3 0.056746093750000004 0.32586111111111116 0.0393359375 0.16944444444444445
3 0.17626171875000002 0.38167361111111114 0.09530468750000001 0.07395833333333333
3 0.28708203125000004 0.3056875 0.024960937499999992 0.06993055555555559
3 0.57185546875 0.3277083333333333 0.03319531250000001 0.057722222222222265
3 0.6347773437500001 0.3692083333333334 0.024804687500000002 0.05772222222222223


FILE: MBDD2025/Labels/Hefei950.txt
1 0.6740742187500001 0.49852083333333336 0.06355468750000003 0.9970416666666667
1 0.57730078125 0.7556666666666667 0.07222656249999995 0.48275
1 0.33680859375000005 0.8226249999999999 0.0794453125 0.35475
1 0.30936328125 0.38975000000000004 0.0592265625 0.27988888888888885
1 0.24003125000000003 0.28025694444444443 0.062109375 0.5605138888888889
1 0.24436328124999998 0.787763888888889 0.04766406250000004 0.38774999999999993


FILE: MBDD2025/Labels/Hefei9500.txt
2 0.26391015625 0.09760416666666667 0.5278203125 0.19520833333333334
2 0.5 0.7188819444444445 1.0 0.24979166666666663


FILE: MBDD2025/Labels/Hefei9501.txt
2 0.275671875 0.08714583333333334 0.55134375 0.17429166666666668
2 0.5 0.6945972222222223 1.0 0.29836111111111113


FILE: MBDD2025/Labels/Hefei9502.txt
2 0.25724609375 0.0790138888888889 0.5097734375 0.1580277777777778
2 0.49901171875000006 0.7119444444444445 0.9980234375000001 0.26366666666666666


FILE: MBDD2025/Labels/Hefei9503.txt
2 0.51990234375 0.732763888888889 0.9484296875 0.2220277777777777
2 0.26992187500000003 0.09528472222222223 0.48885937500000004 0.1789305555555556


FILE: MBDD2025/Labels/Hefei9504.txt
2 0.5 0.7154166666666666 1.0 0.1595833333333333
2 0.271625 0.09296527777777779 0.47056250000000005 0.16731944444444444


FILE: MBDD2025/Labels/Hefei9505.txt
2 0.2729296875 0.09064583333333334 0.48885937500000004 0.17195833333333335
2 0.5 0.7223541666666667 1.0 0.1457083333333333


FILE: MBDD2025/Labels/Hefei9506.txt
2 0.503328125 0.7223611111111111 0.9933437500000001 0.20122222222222214
2 0.26705078125 0.09993055555555555 0.4823203125 0.18125


FILE: MBDD2025/Labels/Hefei9507.txt
2 0.244828125 0.09645138888888888 0.4770937500000001 0.19287500000000002
2 0.5 0.7154166666666666 1.0 0.1734722222222222


FILE: MBDD2025/Labels/Hefei9508.txt
2 0.5 0.725826388888889 1.0 0.20815277777777771
2 0.25855468750000005 0.08598611111111111 0.48885937500000004 0.17197222222222222


FILE: MBDD2025/Labels/Hefei9509.txt
2 0.5 0.7188888888888888 1.0 0.16652777777777775
2 0.23829296875000006 0.09063888888888888 0.46141406250000006 0.18125


FILE: MBDD2025/Labels/Hefei951.txt
1 0.23208984375000005 0.8136319444444445 0.08666406250000001 0.37273611111111116
1 0.3266953125 0.8264722222222222 0.07943750000000001 0.34705555555555556
1 0.31080859375000003 0.4192777777777778 0.05055468749999999 0.27219444444444446
1 0.24373828125000002 0.25838194444444446 0.043335937500000025 0.5167638888888889
1 0.66093359375 0.47558333333333336 0.05657031250000007 0.9511666666666667
1 0.5772812500000001 0.7553611111111111 0.06981250000000001 0.4258333333333333


FILE: MBDD2025/Labels/Hefei9510.txt
2 0.23894531250000003 0.09529166666666669 0.46271875 0.18125
2 0.5 0.736236111111111 1.0 0.20122222222222222


FILE: MBDD2025/Labels/Hefei9511.txt
2 0.495109375 0.7743958333333334 0.99021875 0.24979166666666672
2 0.22992578125000002 0.09529166666666669 0.45985156250000003 0.18125


FILE: MBDD2025/Labels/Hefei9512.txt
2 0.52869921875 0.7084791666666667 0.9426015625 0.1457083333333333
2 0.23371874999999998 0.09295833333333335 0.46271875 0.1859166666666667


FILE: MBDD2025/Labels/Hefei9513.txt
2 0.215546875 0.07902083333333335 0.43109375 0.14870833333333336
2 0.5 0.7050138888888889 1.0 0.16652777777777766


FILE: MBDD2025/Labels/Hefei9514.txt
2 0.21946875000000002 0.10690277777777778 0.43893750000000004 0.19519444444444448
2 0.5 0.6980694444444445 1.0 0.20816666666666658


FILE: MBDD2025/Labels/Hefei9515.txt
2 0.501375 0.732763888888889 0.9972500000000001 0.2498055555555555
2 0.21293359375 0.09877083333333334 0.4258671875 0.1789305555555556


FILE: MBDD2025/Labels/Hefei9516.txt
2 0.21293359375 0.09644444444444444 0.4258671875 0.1928888888888889
2 0.5 0.7050069444444444 1.0 0.19429166666666658


FILE: MBDD2025/Labels/Hefei9517.txt
2 0.20639453125 0.09179861111111111 0.4127890625 0.17893055555555554
2 0.5 0.7050138888888889 1.0 0.16652777777777766


FILE: MBDD2025/Labels/Hefei9518.txt
2 0.500125 0.704263888888889 0.9997500000000001 0.2038333333333334
2 0.20365625 0.08947916666666667 0.38690625 0.1789305555555556


FILE: MBDD2025/Labels/Hefei9519.txt
2 0.5 0.7462361111111111 1.0 0.26377777777777783
2 0.18809765625 0.10457638888888887 0.3761953125 0.17195833333333332


FILE: MBDD2025/Labels/Hefei952.txt
1 0.5845000000000001 0.7776458333333334 0.07943749999999997 0.44470833333333337
1 0.6711640625 0.5 0.07462499999999998 1.0
1 0.32450390625000003 0.8270486111111112 0.08425781250000003 0.32954166666666673
1 0.24867187500000001 0.8247222222222222 0.06740624999999999 0.35055555555555556
1 0.2396484375 0.26694444444444443 0.046937500000000035 0.5338888888888889
1 0.306453125 0.40443055555555557 0.033703124999999994 0.2546388888888889


FILE: MBDD2025/Labels/Hefei9520.txt
2 0.5 0.6922777777777778 1.0 0.1558611111111111
2 0.20169531250000003 0.1255 0.39343750000000005 0.16730555555555557


FILE: MBDD2025/Labels/Hefei9521.txt
2 0.20039062500000002 0.11736111111111111 0.38298437500000004 0.16033333333333333
2 0.4992109375 0.6982708333333334 0.998421875 0.2158194444444445


FILE: MBDD2025/Labels/Hefei9522.txt
2 0.5136171875 0.6682986111111111 0.9727656250000001 0.2517916666666668
2 0.19201953125000001 0.10458333333333335 0.38403906250000003 0.14408333333333334


FILE: MBDD2025/Labels/Hefei9523.txt
2 0.185484375 0.10922916666666668 0.37096875 0.17195833333333335
2 0.48922265624999994 0.6742916666666667 0.9509609375000001 0.16786111111111104


FILE: MBDD2025/Labels/Hefei9524.txt
2 0.500125 0.6922777777777778 0.9997500000000001 0.1558611111111111

In [ ]:
import zipfile

archive_path = "/content/MBDD2025.zip"

with zipfile.ZipFile(archive_path, "r") as f:
    # Find the first few label files
    label_files = [i for i in f.namelist() if i.startswith("MBDD2025/Labels/") and i.endswith(".txt")][:5]
    print("Sample annotation files:\n")
    for j in label_files:
        print(f"--- {j} ---")
        content = f.read(j).decode("utf-8", errors="replace")
        print(repr(content[:500]))
        print()

Sample annotation files:

--- MBDD2025/Labels/Hefei1.txt ---
'3 0.5084765625000001 0.35477083333333337 0.06426562499999999 0.15104166666666669\r\n'

--- MBDD2025/Labels/Hefei10.txt ---
'3 0.52306640625 0.3470277777777778 0.05882031249999997 0.13166666666666665\r\n'

--- MBDD2025/Labels/Hefei100.txt ---
'3 0.018199218750000003 0.32330555555555557 0.0326796875 0.16136111111111112\r\n3 0.13121093749999999 0.37252777777777785 0.11709375 0.06938888888888886\r\n3 0.24467578124999997 0.3152361111111111 0.035398437500000005 0.05486111111111111\r\n3 0.51834765625 0.3225 0.043570312499999986 0.06294444444444448\r\n3 0.58143359375 0.3692986111111111 0.03358593750000001 0.06293055555555556\r\n'

--- MBDD2025/Labels/Hefei1000.txt ---
'1 0.68452734375 0.5966111111111111 0.08425781250000003 0.8067777777777778\r\n2 0.30432421875000004 0.40232638888888883 0.0633828125 0.12631944444444443\r\n'

--- MBDD2025/Labels/Hefei10000.txt ---
'0 0.10098828124999999 0.6375069444444444 0.20066406250000002 0.15595833333333328\r\n0 0.35875781250000005 0.41702083333333334 0.21642187500000004 0.14848611111111107\r\n0 0.11411328125 0.38604166666666667 0.2282265625 0.09805555555555555\r\n'

In [ ]:
# Finding the class names
with zipfile.ZipFile(archive_path, "r") as f:
    # Looking for the dataset README and annotation metadata
    candidates = [i for i in f.namelist() if i.lower().endswith(("readme.md", "data.yaml", "dataset.yaml", "classes.txt"))]

    print("Metadata files found:", candidates)
    for i in candidates:
        print(f"\n--- {i} ---")
        content = f.read(i).decode("utf-8", errors="replace")
        print(content[:5000])

    # Inspecting an XML annotation to find the original defect class names
    xml_files = [i for i in f.namelist() if i.startswith("MBDD2025/Annotations/") and i.endswith(".xml")]
    if xml_files:
        print("\n--- Sample XML annotation ---")
        xml = f.read(xml_files[0]).decode("utf-8", errors="replace")
        print(xml[:3000])

Metadata files found: ['MBDD2025/README.md']

--- MBDD2025/README.md ---
# MBDD2025: A Deep Learning-Oriented Dataset for Diverse Building Defect Detection from UAV Images

## 📂 Dataset Overview

**MBDD2025** is a large-scale dataset of building wall defects collected via UAV imagery. The dataset is designed for object detection and classification tasks in the field of intelligent building inspection. It includes a wide range of structural types and defect categories, making it suitable for generalization across various real-world scenarios.

- **Total images**: 14,471
- **Image resolution**: High-resolution UAV photos
- **Defect types (5)**:
  - Crack
  - Leakage
  - Abscission
  - Corrosion
  - Bulge

- **Building structure types (6)**:
  - Steel structure
  - Wooden structure
  - Masonry structure
  - Brick and wood structure
  - Brick concrete structure
  - Reinforced concrete structure

- **Annotation format**: VOC XML
- **Compression format**: `.zip`

---

## 📁 Folder Structure
MBDD2025/
├── JPEGImages/ # Original UAV images
├── Annotations/ # VOC XML annotation files
├── Labels/ # Optional class label file (if available)
└── README.md # This file

---

## 🧾 Annotation Format

- Annotation files are in **PASCAL VOC XML** format.
- Each XML file corresponds to an image and contains:
  - Bounding boxes
  - Object class labels (defects only)
  - Image size and metadata

---

## 🚀 Usage

This dataset can be used to train object detection models such as:

- [Faster R-CNN](https://arxiv.org/abs/1506.01497)
- [YOLOv5/YOLOv8](https://github.com/ultralytics/yolov5)

### Steps:

1. Download and unzip the dataset:

unzip MBDD2025.zip
cd MBDD2025

2. Use tools like [MMDetection](https://github.com/open-mmlab/mmdetection) or Ultralytics YOLO to train on the VOC format.

3. Make sure to convert labels if needed (e.g., to COCO or YOLO format).

---

## 📜 License

This dataset is released under the **Creative Commons Attribution 4.0 International License (CC BY 4.0)**.
You are free to use, share, and adapt the dataset, provided appropriate credit is given.

---

## 📣 Citation

If you use **MBDD2025** in your research, please cite the dataset as follows:

@misc{MBDD2025,
title = {MBDD2025: A Deep Learning-Oriented Dataset for Diverse Building Defect Detection from UAV Images},
author = {Qikai Zha,Yiming Yao,Wenkang Zhang,Wanqi Ma},
year = {2025},
publisher = {Zenodo},
doi = {https://doi.org/10.5281/zenodo.15622584}
}

> 📌 *Replace `Your Name(s)` and `DOI` with the actual author(s) and DOI once the dataset is published on Zenodo.*

---

## 💬 Contact

If you have any questions or suggestions, feel free to open an issue or contact the dataset maintainer.


--- Sample XML annotation ---
<?xml version='1.0' encoding='utf-8'?>
<annotation>
  <folder>/dji</folder>
  <filename>1.jpg</filename>
  <source>
    <database>Unknown</database>
    <annotation>Unknown</annotation>
    <image>Unknown</image>
  </source>
  <size>
    <width>1280</width>
    <height>720</height>
    <depth />
  </size>
  <segmented>0</segmented>
  <object>
    <name>corrosion</name>
    <truncated>0</truncated>
    <occluded>0</occluded>
    <difficult>0</difficult>
    <bndbox>
      <xmin>609.72</xmin>
      <ymin>201.06</ymin>
      <xmax>691.98</xmax>
      <ymax>309.81</ymax>
    </bndbox>
    <attributes>
      <attribute>
        <name>rotation</name>
        <value>0.0</value>
      </attribute>
    </attributes>
  </object>
</annotation>

In [ ]:
# Verifying every defect class and check for structural labels
defect_counts = Counter()
structure_terms = Counter()
xml_count = 0
xml_errors = 0

possible_structure_labels = {
    "steel structure",
    "wooden structure",
    "masonry structure",
    "brick and wood structure",
    "brick concrete structure",
    "reinforced concrete structure",
}

with zipfile.ZipFile(archive_path, "r") as f:
  xml_files = [i for i in f.namelist() if i.startswith("MBDD2025/Annotations/") and i.lower().endswith(".xml")]
  xml_count = len(xml_files)

  for j in xml_files:
    try:
      root = ET.fromstring(f.read(j))

      # Counting object-level defect labels
      for k in root.findall(".//object"):
        name = k.findtext("name", default="").strip().lower()
        if name:
          defect_counts[name] = defect_counts[name]+1

      # Checking all XML text for explicit structure labels
      xml_text = " ".join(text.strip().lower() for text in root.itertext() if text and text.strip())
      for k in possible_structure_labels:
        if k in xml_text:
          structure_terms[k] = structure_terms[k]+1

    except ET.ParseError:
      xml_errors = xml_errors+1

print("XML annotation files:", xml_count)
print("XML parsing errors:", xml_errors)

print("\nDefect class counts (annotated objects):")
for name, count in sorted(defect_counts.items()):
    print(f"{name}: {count}")

print("\nXML files containing explicit structure-type terms:")
if structure_terms:
    for name, count in sorted(structure_terms.items()):
        print(f"{name}: {count} files")
else:
    print("No explicit structure-type terms found.")

XML annotation files: 14471
XML parsing errors: 0

Defect class counts (annotated objects):
abscission: 22702
bulge: 2018
corrosion: 9207
crack: 17044
leakage: 6642

XML files containing explicit structure-type terms:
No explicit structure-type terms found.

In [ ]:
from pathlib import PurePosixPath

In [ ]:
with zipfile.ZipFile(archive_path, "r") as f:
  names = f.namelist()
  images = [i for i in names if i.startswith("MBDD2025/JPEGImages/") and PurePosixPath(i).suffix.lower() in {".jpg", ".jpeg", ".png"}]
  annotations = [i for i in names if i.startswith("MBDD2025/Annotations/") and i.lower().endswith(".xml")]

  imageStems = Counter(PurePosixPath(i).stem for i in images)
  annotationStems = Counter(PurePosixPath(i).stem for i in annotations)

  print("Images: ", len(images))
  print("XML annotations: ", len(annotations))
  print("Images without matching XML: ", len(imageStems-annotationStems))
  print("XML without matching image: ", len(annotationStems-imageStems))
  print("\nSample image paths: ")
  print(*images[:5], sep="\n")
  print("\nSample annotation paths: ")
  print(*annotations[:5], sep="\n")

Images:  14471
XML annotations:  14471
Images without matching XML:  0
XML without matching image:  0

Sample image paths:
MBDD2025/JPEGImages/Hefei1.jpg
MBDD2025/JPEGImages/Hefei10.jpg
MBDD2025/JPEGImages/Hefei100.jpg
MBDD2025/JPEGImages/Hefei1000.jpg
MBDD2025/JPEGImages/Hefei10000.jpg

Sample annotation paths:
MBDD2025/Annotations/Hefei1.xml
MBDD2025/Annotations/Hefei10.xml
MBDD2025/Annotations/Hefei100.xml
MBDD2025/Annotations/Hefei1000.xml
MBDD2025/Annotations/Hefei10000.xml

In [28]:
import zipfile
import xml.etree.ElementTree as ET

from pathlib import PurePosixPath
from PIL import Image
from io import BytesIO
from collections import Counter

archive_path = "/content/MBDD2025.zip"

checked = 0
badImages = []
badBoxes = []
emptyAnnotations = 0
defect_counts = Counter()
image_sizes = Counter()

with zipfile.ZipFile(archive_path, "r") as f:
  xml_files = [i for i in f.namelist() if i.startswith("MBDD2025/Annotations/") and i.lower().endswith(".xml")]
  for j in xml_files:
    stem = PurePosixPath(j).stem
    image_name = f"MBDD2025/JPEGImages/{stem}.jpg"
    try:
      image = Image.open(BytesIO(f.read(image_name)))
      image.verify()
      image = Image.open(BytesIO(f.read(image_name)))
      width, height = image.size
      image_sizes[(width,height)] = image_sizes[(width,height)]+1
      root = ET.fromstring(f.read(j))
      objects = root.findall("object")
      if objects:
        emptyAnnotations = emptyAnnotations+1
        for k in objects:
          label = k.findtext("name", "").strip().lower()
          defect_counts[label] = defect_counts[label]+1
          box = k.find("bndbox")
          if box is None:
            badBoxes.append((j, "missing box"))
            continue

          xmin = float(box.findtext("xmin"))
          ymin = float(box.findtext("ymin"))

          xmax = float(box.findtext("xmax"))
          ymax = float(box.findtext("ymax"))

          if not (0<=xmin<xmax<=width and 0<=ymin<ymax<=height):
            badBoxes.append((j, (xmin, ymin, xmax, ymax), (width, height)))
        checked = checked+1

    except Exception as e:
      badImages.append((image_name, str(e)))

print("Images and annotations checked:", checked)
print("Image decoding/errors:", len(badImages))
print("Invalid bounding boxes:", len(badBoxes))
print("Images with no annotated objects:", emptyAnnotations)

print("\nImage dimensions (top 10):")
for size, count in image_sizes.most_common(10):
    print(f"{size}: {count}")

print("\nDefect instance counts:")
for label, count in sorted(defect_counts.items()):
    print(f"{label}: {count}")

print("\nSample errors:")
print("Images:", badImages[:3])
print("Boxes:", badBoxes[:3])

Images and annotations checked: 14463
Image decoding/errors: 0
Invalid bounding boxes: 116
Images with no annotated objects: 14463

Image dimensions (top 10):
(1280, 720): 14102
(720, 1280): 254
(960, 544): 115

Defect instance counts:
abscission: 22702
bulge: 2018
corrosion: 9207
crack: 17044
leakage: 6642

Sample errors:
Images: []
Boxes: [('MBDD2025/Annotations/Hefei11420.xml', (-7.75, 135.09, 201.8, 165.1), (1280, 720)), ('MBDD2025/Annotations/Hefei11421.xml', (-18.96, 127.34, 226.97, 158.32), (1280, 720)), ('MBDD2025/Annotations/Hefei11422.xml', (-9.97, 118.36, 216.08, 153.73), (1280, 720))]

In [29]:
import zipfile
import xml.etree.ElementTree as ET

from collections import Counter

archive_path = "/content/MBDD2025.zip"

with zipfile.ZipFile(archive_path, "r") as f:
    xml_files = [i for i in f.namelist() if i.startswith("MBDD2025/Annotations/") and i.endswith(".xml")]

    empty_count = 0
    nonempty_count = 0
    object_counts = Counter()

    for j in xml_files:
        root = ET.fromstring(f.read(j))
        objects = root.findall("object")

        if len(objects) == 0:
            empty_count = empty_count+1

        else:
            nonempty_count = nonempty_count+1
            object_counts[len(objects)] = object_counts[len(objects)]+1

    print("Total XML files:", len(xml_files))
    print("Empty annotations:", empty_count)
    print("Annotations with objects:", nonempty_count)
    print("Object counts per image:", object_counts.most_common(10))

    sample = ET.fromstring(f.read("MBDD2025/Annotations/Hefei11420.xml"))

    print("\nHefei11420 object names:")
    for k in sample.findall("object"):
        print(k.findtext("name"), k.find("bndbox") is not None)

Total XML files: 14471
Empty annotations: 8
Annotations with objects: 14463
Object counts per image: [(1, 4081), (2, 3560), (3, 1848), (4, 1257), (5, 779), (6, 729), (7, 401), (10, 230), (8, 225), (9, 225)]

Hefei11420 object names:
abscission True
abscission True
crack True
abscission True
abscission True
abscission True
abscission True
abscission True
abscission True
abscission True
abscission True
crack True

In [30]:
# Inspecting the 8 empty annotations
import zipfile
import xml.etree.ElementTree as ET

In [31]:
from pathlib import PurePosixPath

In [33]:
with zipfile.ZipFile(archive_path, "r") as f:
  for i in f.namelist():
    if (i.startswith("MBDD2025/Annotations/") and i.endswith(".xml")):
      root = ET.fromstring(f.read(i))
      if not root.findall("object"):
        stem = PurePosixPath(i).stem
        image_name = f"MBDD2025/JPEGImages/{stem}.jpg"

        print("Empty annotation:", i)
        print("Matching image exists:", image_name in f.namelist())
        print()

Empty annotation: MBDD2025/Annotations/Hefei10237.xml
Matching image exists: True

Empty annotation: MBDD2025/Annotations/Hefei10278.xml
Matching image exists: True

Empty annotation: MBDD2025/Annotations/Hefei10421.xml
Matching image exists: True

Empty annotation: MBDD2025/Annotations/Hefei13256.xml
Matching image exists: True

Empty annotation: MBDD2025/Annotations/Hefei1821.xml
Matching image exists: True

Empty annotation: MBDD2025/Annotations/Hefei425.xml
Matching image exists: True

Empty annotation: MBDD2025/Annotations/Hefei901.xml
Matching image exists: True

Empty annotation: MBDD2025/Annotations/Hefei9028.xml
Matching image exists: True

In [35]:
# Inspecting the 116 invalid bounding boxes
import zipfile
import xml.etree.ElementTree as ET

from collections import Counter

archive_path = "/content/MBDD2025.zip"

invalid_count = 0
clippable_count = 0
unusable_count = 0
issues_by_type = Counter()
examples = []

with zipfile.ZipFile(archive_path, "r") as f:
    xml_files = [i for i in f.namelist() if i.startswith("MBDD2025/Annotations/") and i.endswith(".xml")]
    for j in xml_files:
        root = ET.fromstring(f.read(j))
        size = root.find("size")
        if size is None:
            continue

        width = int(size.findtext("width"))
        height = int(size.findtext("height"))

        for k in root.findall("object"):
            box = k.find("bndbox")
            if box is None:
                continue

            xmin = float(box.findtext("xmin"))
            ymin = float(box.findtext("ymin"))

            xmax = float(box.findtext("xmax"))
            ymax = float(box.findtext("ymax"))

            if not (0<=xmin<xmax<=width and 0<=ymin<ymax<=height):
                invalid_count = invalid_count+1

                clipped_xmin = max(0, min(xmin, width))
                clipped_ymin = max(0, min(ymin, height))
                clipped_xmax = max(0, min(xmax, width))
                clipped_ymax = max(0, min(ymax, height))

                if (clipped_xmin<clipped_xmax and clipped_ymin<clipped_ymax):
                    clippable_count = clippable_count+1
                    issue = "clippable"

                else:
                    unusable_count = unusable_count-1
                    issue = "unusable"

                issues_by_type[issue] = issues_by_type[issue]+1

                if len(examples) < 10:
                    examples.append((j, k.findtext("name"), (xmin, ymin, xmax, ymax), (clipped_xmin, clipped_ymin, clipped_xmax, clipped_ymax)))

print("Invalid boxes:", invalid_count)
print("Boxes that remain valid after clipping:", clippable_count)
print("Boxes unusable after clipping:", unusable_count)

print("\nFirst 10 examples:")
for i in examples:
    print(i)

Invalid boxes: 116
Boxes that remain valid after clipping: 116
Boxes unusable after clipping: 0

First 10 examples:
('MBDD2025/Annotations/Hefei11420.xml', 'crack', (-7.75, 135.09, 201.8, 165.1), (0, 135.09, 201.8, 165.1))
('MBDD2025/Annotations/Hefei11421.xml', 'crack', (-18.96, 127.34, 226.97, 158.32), (0, 127.34, 226.97, 158.32))
('MBDD2025/Annotations/Hefei11422.xml', 'crack', (-9.97, 118.36, 216.08, 153.73), (0, 118.36, 216.08, 153.73))
('MBDD2025/Annotations/Hefei11423.xml', 'crack', (-14.12, 110.88, 270.54, 152.51), (0, 110.88, 270.54, 152.51))
('MBDD2025/Annotations/Hefei11424.xml', 'crack', (-13.15, 103.13, 247.29999999999998, 143.8), (0, 103.13, 247.29999999999998, 143.8))
('MBDD2025/Annotations/Hefei11425.xml', 'crack', (-5.79, 111.0, 259.89, 147.8), (0, 111.0, 259.89, 147.8))
('MBDD2025/Annotations/Hefei11426.xml', 'crack', (-18.4, 93.45, 280.22, 150.58), (0, 93.45, 280.22, 150.58))
('MBDD2025/Annotations/Hefei11427.xml', 'crack', (-16.96, 95.0, 279.99, 146.31), (0, 95.0, 279.99, 146.31))
('MBDD2025/Annotations/Hefei11428.xml', 'crack', (-10.86, 100.67, 281.25, 143.89), (0, 100.67, 281.25, 143.89))
('MBDD2025/Annotations/Hefei11429.xml', 'crack', (-23.8, 97.33, 262.79, 132.18), (0, 97.33, 262.79, 132.18))

In [37]:
# Performing the 80/10/10 split
# 80% Training, 10% Validation, 10% Testing
import zipfile
import xml.etree.ElementTree as ET
import pandas as pd

In [38]:
from pathlib import PurePosixPath
from collections import Counter
from sklearn.model_selection import train_test_split

In [40]:
archive_path = "/content/MBDD2025.zip"
random_seed = 42

class_names = ["abscission", "bulge", "corrosion", "crack", "leakage"]
records = []

excludedEmpty = 0
excludedMulti = 0
excludedUnknown = 0

with zipfile.ZipFile(archive_path, "r") as f:
  xml_files = [i for i in f.namelist() if i.startswith("MBDD2025/Annotations/") and i.endswith(".xml")]
  for j in xml_files:
    root = ET.fromstring(f.read(j))
    objects = root.findall("object")

    labels = {
        k.findtext("name", "").strip().lower() for k in objects if k.findtext("name", "").strip()
    }

    if not labels:
      excludedEmpty = excludedEmpty+1
      continue

    if not labels.issubset(set(class_names)):
      excludedUnknown = excludedUnknown+1
      continue

    if len(labels)!=1:
      excludedMulti = excludedMulti+1
      continue

    image_name = PurePosixPath(j).stem+".jpg"
    records.append(
        {
            "image": image_name,
            "label": next(iter(labels))
        }
    )

  load = pd.DataFrame(records)

# Split 80% train, 20% temporary
train, temp = train_test_split(load, test_size=0.20, random_state=random_seed, stratify=load["label"],)

# Splitting temporary data equally into validation and test
validation, test = train_test_split(temp, test_size=0.50, random_state=random_seed, stratify=temp["label"],)

train = train.copy()
validation = validation.copy()
test = test.copy()

train["split"] = "train"
validation["split"] = "validation"
test["split"] = "test"

manifest = pd.concat([train, validation, test], ignore_index=True,)
manifest.to_csv("/content/mbdd_classification_manifest.csv", index=False,)

print("Excluded empty annotations:", excludedEmpty)
print("Excluded multi-category images:", excludedMulti)
print("Excluded unknown-label images:", excludedUnknown)

print("\nSplit sizes:")
print("Train:", len(train))
print("Validation:", len(validation))
print("Test:", len(test))
print("Total:", len(manifest))

print("\nClass distribution by split:")
print(pd.crosstab(manifest["label"], manifest["split"]))

print("\nManifest saved to:")
print("/content/mbdd_classification_manifest.csv")

Excluded empty annotations: 8
Excluded multi-category images: 2399
Excluded unknown-label images: 0

Split sizes:
Train: 9651
Validation: 1206
Test: 1207
Total: 12064

Class distribution by split:
split       test  train  validation
label
abscission   334   2672         334
bulge         75    600          75
corrosion    166   1330         166
crack        437   3490         436
leakage      195   1559         195

Manifest saved to:
/content/mbdd_classification_manifest.csv

In [41]:
import pandas as pd

manifest = pd.read_csv("/content/mbdd_classification_manifest.csv")

print("Total rows:", len(manifest))
print("Unique image filenames:", manifest["image"].nunique())
print("Duplicate filenames:", manifest["image"].duplicated().sum())

print("\nImages per split:")
print(manifest["split"].value_counts())

print("\nImages assigned to multiple splits:")
split_counts = manifest.groupby("image")["split"].nunique()
print((split_counts > 1).sum())

Total rows: 12064
Unique image filenames: 12064
Duplicate filenames: 0

Images per split:
split
train         9651
test          1207
validation    1206
Name: count, dtype: int64

Images assigned to multiple splits:
0

In [16]:
import zipfile
import xml.etree.ElementTree as ET
import pandas as pd

from sklearn.model_selection import train_test_split
from pathlib import PurePosixPath

archive_path = "/content/drive/MyDrive/DistributedAIProject/MBDD2025.zip"
output_path = "/content/drive/MyDrive/DistributedAIProject/mbdd_classification_manifest.csv"

random_seed = 42
class_names = {"abscission", "bulge", "corrosion", "crack", "leakage"}

records = []
excludedEmpty = 0
excludedMulti = 0
excludedUnknown = 0

with zipfile.ZipFile(archive_path, "r") as f:
    xml_files = [i for i in f.namelist() if i.startswith("MBDD2025/Annotations/") and i.endswith(".xml")]
    for j in xml_files:
        root = ET.fromstring(f.read(j))
        labels = {
            k.findtext("name", "").strip().lower()
            for k in root.findall("object")
            if k.findtext("name", "").strip()
        }

        if not labels:
            excludedEmpty = excludedEmpty+1
            continue

        if not labels.issubset(class_names):
            excludedUnknown = excludedUnknown+1
            continue

        if len(labels) != 1:
            excludedMulti = excludedMulti+1
            continue

        records.append({
            "image": PurePosixPath(j).stem + ".jpg",
            "label": next(iter(labels)),
        })

load = pd.DataFrame(records)

train, temp = train_test_split(load, test_size=0.20, random_state=random_seed, stratify=load["label"])
validation, test = train_test_split(temp, test_size=0.50, random_state=random_seed, stratify=temp["label"])

train = train.copy()
validation = validation.copy()
test = test.copy()

train["split"] = "train"
validation["split"] = "validation"
test["split"] = "test"

manifest = pd.concat([train, validation, test], ignore_index=True)
manifest.to_csv(output_path, index=False)

print("Annotations:", len(xml_files))
print("Excluded empty:", excludedEmpty)
print("Excluded multi-category:", excludedMulti)
print("Excluded unknown labels:", excludedUnknown)
print("\nSplit sizes:")
print(manifest["split"].value_counts())
print("\nClass distribution:")
print(pd.crosstab(manifest["label"], manifest["split"]))
print("\nSaved permanently to:", output_path)

Annotations: 14471
Excluded empty: 8
Excluded multi-category: 2399
Excluded unknown labels: 0

Split sizes:
split
train         9651
test          1207
validation    1206
Name: count, dtype: int64

Class distribution:
split       test  train  validation
label
abscission   334   2672         334
bulge         75    600          75
corrosion    166   1330         166
crack        437   3490         436
leakage      195   1559         195

Saved permanently to: /content/drive/MyDrive/DistributedAIProject/mbdd_classification_manifest.csv

In [17]:
# Duplicate Check
import pandas as pd
import zipfile
import hashlib

archive_path = ("/content/drive/MyDrive/DistributedAIProject/MBDD2025.zip")
manifest_path = (
    "/content/drive/MyDrive/DistributedAIProject/"
    "mbdd_classification_manifest.csv"
)

manifest = pd.read_csv(manifest_path)
hashRecords = []

with zipfile.ZipFile(archive_path, "r") as f:
  for i, j in enumerate(manifest.itertuples(index=False), start=1):
    imagePath = "MBDD2025/JPEGImages/"+j.image
    with f.open(imagePath) as imageFile:
      digest = hashlib.sha256(imageFile.read()).hexdigest()
    hashRecords.append(
        {
            "image": j.image,
            "split": j.split,
            "label": j.label,
            "sha256": digest,
        }
    )

    if i%2000 == 0:
      print(f"Checked {i}/{len(manifest)} images")

hash_load = pd.DataFrame(hashRecords)

Checked 2000/12064 images
Checked 4000/12064 images
Checked 6000/12064 images
Checked 8000/12064 images
Checked 10000/12064 images
Checked 12000/12064 images

In [20]:
import zipfile
import hashlib
import pandas as pd

from pathlib import Path

PROJECT_DIR = Path(
    "/content/drive/MyDrive/DistributedAIProject"
)

archive_path = PROJECT_DIR / "MBDD2025.zip"
manifest_path = PROJECT_DIR / "mbdd_classification_manifest.csv"
checkpoint_path = PROJECT_DIR / "image_hash_checkpoint.csv"

manifest = pd.read_csv(manifest_path)

# Resume from the existing checkpoint, if available
if checkpoint_path.exists():
    saved = pd.read_csv(checkpoint_path)
    hashRecords = saved.to_dict("records")
    completed = {i["image"] for i in hash_records}
    print("Resuming from checkpoint:", len(completed), "images")

else:
    hashRecords = []
    completed = set()
    print("Starting a new hash check")

with zipfile.ZipFile(archive_path, "r") as f:
    for i, j in enumerate(manifest.itertuples(index=False), start=1):
        if j.image in completed:
            continue

        image_path = "MBDD2025/JPEGImages/" + j.image

        with f.open(image_path) as image_file:
            digest = hashlib.sha256(image_file.read()).hexdigest()

        hashRecords.append(
            {
                "image": j.image,
                "split": j.split,
                "label": j.label,
                "sha256": digest,
            }
        )

        completed.add(j.image)

        if len(hashRecords)%500 == 0:
            pd.DataFrame(hashRecords).to_csv(checkpoint_path, index=False)
            print("Checkpoint saved:", len(hashRecords))

# Save the final complete result
hash_load = pd.DataFrame(hashRecords)
hash_load.to_csv(checkpoint_path, index=False)

print("\nImages hashed:", len(hash_load))
print("Checkpoint saved to:", checkpoint_path)

Starting a new hash check
Checkpoint saved: 500
Checkpoint saved: 1000
Checkpoint saved: 1500
Checkpoint saved: 2000
Checkpoint saved: 2500
Checkpoint saved: 3000
Checkpoint saved: 3500
Checkpoint saved: 4000
Checkpoint saved: 4500
Checkpoint saved: 5000
Checkpoint saved: 5500
Checkpoint saved: 6000
Checkpoint saved: 6500
Checkpoint saved: 7000
Checkpoint saved: 7500
Checkpoint saved: 8000
Checkpoint saved: 8500
Checkpoint saved: 9000
Checkpoint saved: 9500
Checkpoint saved: 10000
Checkpoint saved: 10500
Checkpoint saved: 11000
Checkpoint saved: 11500
Checkpoint saved: 12000

Images hashed: 12064
Checkpoint saved to: /content/drive/MyDrive/DistributedAIProject/image_hash_checkpoint.csv

In [22]:
# Checking cross-split duplicates
import pandas as pd

hash_load = pd.read_csv(
    "/content/drive/MyDrive/DistributedAIProject/"
    "image_hash_checkpoint.csv"
)

duplicate_groups = hash_load.groupby("sha256").filter(lambda group: group["split"].nunique() > 1)

print("Images hashed:", len(hash_load))
print("Images in cross-split exact-duplicate groups:", duplicate_groups["image"].nunique())

if not duplicate_groups.empty:
    display(duplicate_groups.sort_values("sha256"))

hash_load.to_csv("/content/drive/MyDrive/DistributedAIProject/" "image_hashes.csv", index=False,)
print("Final hash results saved.")

Images hashed: 12064
Images in cross-split exact-duplicate groups: 109

,image,split,label,sha256
11122,Hefei4365.jpg,test,bulge,00886662c03a7fa67f772f27401b309eaf75f3dc6ee3ea...
5935,Hefei4009.jpg,train,bulge,00886662c03a7fa67f772f27401b309eaf75f3dc6ee3ea...
6665,Hefei4032.jpg,train,bulge,0a5299c71ebeb7d6f552ceed3e848690c09638892d109f...
10935,Hefei4434.jpg,test,bulge,0a5299c71ebeb7d6f552ceed3e848690c09638892d109f...
1755,Hefei3938.jpg,train,bulge,0df48f46f3f7f58ad8f3360dbe2f4656ab554f4383c842...
...,...,...,...,...
10631,Hefei3969.jpg,validation,bulge,f78776572a42cc7b8731ae55725eb6d31af0ddec67d757...
348,Hefei4017.jpg,train,bulge,fddc670e6db308f505ce3b17e333635d997525c8c494e9...
11134,Hefei4389.jpg,test,bulge,fddc670e6db308f505ce3b17e333635d997525c8c494e9...
9864,Hefei4185.jpg,validation,bulge,feff4608ea2d91ce2e48440749ba23f4053c53fb6d21e2...
3049,Hefei3949.jpg,train,bulge,feff4608ea2d91ce2e48440749ba23f4053c53fb6d21e2...

Final hash results saved.

In [24]:
# Building duplicate groups
import pandas as pd

PROJECT_DIR = "/content/drive/MyDrive/DistributedAIProject"

hash_load = pd.read_csv(f"{PROJECT_DIR}/image_hashes.csv")
manifest = pd.read_csv(f"{PROJECT_DIR}/mbdd_classification_manifest.csv")

# Each identical file-content group receives one group ID
hash_load["duplicate_group"] = (hash_load.groupby("sha256", sort=False).ngroup())

# Counting group that span more than one split
group_summary = hash_load.groupby("duplicate_group").agg(
    image_count=("image", "size"),
    split_count=("split", "nunique"),
    splits=("split", lambda x: ", ".join(sorted(set(x)))),
    labels=("label", lambda x: ", ".join(sorted(set(x)))),
)

cross_split_groups = group_summary[group_summary["split_count"] > 1].sort_values("image_count", ascending=False)

print("Total images: ", len(hash_load))
print("Unique content groups: ", hash_load["sha256"].nunique())
print("Groups spanning multiple splits: ", len(cross_split_groups))
print("Images in those groups: ", int(cross_split_groups["image_count"].sum()))

display(cross_split_groups.head(20))
cross_split_groups.to_csv(f"{PROJECT_DIR}/cross_split_duplicate_groups.csv")

print("\nDuplicate group report saved to Google Drive.")

Total images:  12064
Unique content groups:  11896
Groups spanning multiple splits:  54
Images in those groups:  109

                 image_count  split_count             splits labels
duplicate_group
5112                       3            2        test, train  bulge
62                         2            2  train, validation  bulge
312                        2            2        test, train  bulge
348                        2            2        test, train  bulge
1171                       2            2  train, validation  bulge
175                        2            2        test, train  bulge
1590                       2            2        test, train  bulge
1751                       2            2        test, train  bulge
1954                       2            2  train, validation  bulge
2016                       2            2  train, validation  bulge
2090                       2            2        test, train  bulge
2182                       2            2  train, validation  bulge
2288                       2            2        test, train  bulge
2381                       2            2  train, validation  bulge
2676                       2            2        test, train  bulge
3041                       2            2  train, validation  bulge
3319                       2            2        test, train  bulge
3355                       2            2        test, train  bulge
3456                       2            2        test, train  bulge
3860                       2            2  train, validation  bulge

Duplicate group report saved to Google Drive.

In [25]:
import pandas as pd
from sklearn.model_selection import train_test_split

PROJECT_DIR = "/content/drive/MyDrive/DistributedAIProject"

manifest = pd.read_csv(f"{PROJECT_DIR}/mbdd_classification_manifest.csv")
hash_load = pd.read_csv(f"{PROJECT_DIR}/image_hashes.csv")

# Attach each image's content hash to the manifest
data = manifest.merge(
    hash_load[["image", "sha256"]],
    on="image",
    how="left",
    validate="one_to_one",
)

assert data["sha256"].notna().all()

# Every identical-content group must remain together
groups = (data.groupby("sha256").agg(label=("label", lambda s: s.mode().iloc[0]), size=("image", "size"),).reset_index())

# Stratify groups by class, weighted approximately by image count.
# Group-level stratification is approximate because duplicate groups can contain different numbers of images.
train_groups, temp_groups = train_test_split(groups, test_size=0.20, random_state=42, stratify=groups["label"],)
validation_groups, test_groups = train_test_split(temp_groups, test_size=0.50, random_state=42, stratify=temp_groups["label"],)

split_by_hash = {}
for i, j in [(train_groups, "train"), (validation_groups, "validation"), (test_groups, "test"),]:
    split_by_hash.update(dict(zip(i["sha256"], [j]*len(i))))

data["split"] = data["sha256"].map(split_by_hash)

# Verifying that exact duplicates do not cross splits
assert data.groupby("sha256")["split"].nunique().max() == 1

corrected = data[["image", "label", "split"]].copy()
output_path = f"{PROJECT_DIR}/mbdd_classification_manifest_deduplicated.csv"
corrected.to_csv(output_path, index=False)

print("Images:", len(corrected))
print("\nSplit sizes:")
print(corrected["split"].value_counts())
print("\nClass distribution:")
print(pd.crosstab(corrected["label"], corrected["split"]))
print("\nCross-split exact-duplicate groups:",
      int((data.groupby("sha256")["split"].nunique() > 1).sum()))
print("\nSaved:", output_path)

Images: 12064

Split sizes:
split
train         9647
validation    1214
test          1203
Name: count, dtype: int64

Class distribution:
split       test  train  validation
label
abscission   334   2672         334
bulge         71    597          82
corrosion    166   1329         167
crack        437   3490         436
leakage      195   1559         195

Cross-split exact-duplicate groups: 0

Saved: /content/drive/MyDrive/DistributedAIProject/mbdd_classification_manifest_deduplicated.csv

In [27]:
# Verifying that the manifest has been saved in Drive
import pandas as pd

PROJECT_DIR = "/content/drive/MyDrive/DistributedAIProject"

manifest = pd.read_csv(f"{PROJECT_DIR}/mbdd_classification_manifest_deduplicated.csv")
hash_load = pd.read_csv(f"{PROJECT_DIR}/image_hashes.csv")

check = manifest.merge(hash_load[["image", "sha256"]], on="image", validate="one_to_one",)
cross_split_groups = (check.groupby("sha256")["split"].nunique() > 1).sum()

print("Manifest rows: ", len(manifest))
print("Unique filenames: ", manifest["image"].nunique())
print("Missing labels: ", manifest["label"].isna().sum())
print("Cross-split exact-duplicate groups: ", cross_split_groups)

assert len(manifest) == 12064
assert manifest["image"].nunique() == 12064
assert cross_split_groups == 0

print("\nValidation passed!")

Manifest rows:  12064
Unique filenames:  12064
Missing labels:  0
Cross-split exact-duplicate groups:  0

Validation passed!

In [28]:
# Inspecting near duplicate checks
import pandas as pd
from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/DistributedAIProject")
manifest = pd.read_csv(PROJECT_DIR / "mbdd_classification_manifest_deduplicated.csv")

In [29]:
# Extracting numeric suffixes from filenames
manifest["sequence_number"] = (manifest["image"].str.extract(r"Hefei(\d+)", expand=False).astype("Int64"))
manifest = manifest.sort_values("sequence_number")

print("Images: ", len(manifest))
print("Images with parsed Hefei numbers: ", manifest["sequence_number"].notna().sum())

Images:  12064
Images with parsed Hefei numbers:  12064

In [30]:
# Inspecting nearby filenames whose images are assigned to different splits
manifest["previous_number"] = manifest["sequence_number"].shift()
manifest["previous_split"] = manifest["split"].shift()
manifest["number_gap"] = (manifest["sequence_number"]-manifest["previous_number"])

nearby_cross_split = manifest[(manifest["number_gap"] > 0) & (manifest["number_gap"] <= 5) & (manifest["split"] != manifest["previous_split"])]

print("\nNearby filename numbers crossing split boundaries:")
display(nearby_cross_split[["image", "sequence_number", "split", "previous_number", "previous_split", "number_gap"]].head(30))

Nearby filename numbers crossing split boundaries:

,image,sequence_number,split,previous_number,previous_split,number_gap
8432,Hefei2.jpg,2,validation,1,train,1
5859,Hefei3.jpg,3,train,2,validation,1
8152,Hefei10.jpg,10,test,9,train,1
11203,Hefei11.jpg,11,train,10,test,1
6346,Hefei15.jpg,15,validation,14,train,1
11182,Hefei16.jpg,16,train,15,validation,1
5742,Hefei21.jpg,21,validation,20,train,1
1856,Hefei23.jpg,23,train,22,validation,1
11946,Hefei43.jpg,43,test,42,train,1
2702,Hefei44.jpg,44,train,43,test,1
9843,Hefei48.jpg,48,test,47,train,1
7265,Hefei49.jpg,49,train,48,test,1
380,Hefei50.jpg,50,test,49,train,1
8411,Hefei51.jpg,51,train,50,test,1
1877,Hefei63.jpg,63,validation,62,train,1
7801,Hefei64.jpg,64,train,63,validation,1
3876,Hefei69.jpg,69,test,68,train,1
4246,Hefei72.jpg,72,train,71,test,1
4946,Hefei73.jpg,73,validation,72,train,1
4697,Hefei74.jpg,74,train,73,validation,1
2860,Hefei78.jpg,78,test,77,train,1
2581,Hefei79.jpg,79,train,78,test,1
461,Hefei81.jpg,81,test,80,train,1
6255,Hefei82.jpg,82,train,81,test,1
10400,Hefei84.jpg,84,test,83,train,1
7089,Hefei85.jpg,85,train,84,test,1
10035,Hefei86.jpg,86,test,85,train,1
5977,Hefei87.jpg,87,train,86,test,1
9783,Hefei96.jpg,96,validation,95,train,1
10167,Hefei97.jpg,97,train,96,validation,1

In [31]:
# Searching for images automatically
import matplotlib.pyplot as plt

from pathlib import Path
from PIL import Image

In [36]:
import pandas as pd

project_dir = Path("/content/drive/MyDrive/DistributedAIProject")
manifest_path = project_dir / "mbdd_classification_manifest_deduplicated.csv"

load = pd.read_csv(manifest_path)

print("Shape:", load.shape)
print("\nColumns:")
print(load.columns.tolist())

print("\nFirst 10 rows:")
display(load.head(10))

print("\nFilename examples:")
filename = next((i for i in load.columns if "filename" in i.lower() or "image" in i.lower()), None)
if filename:
    print(load[filename].astype(str).sample(min(20, len(load)), random_state=42).to_list())

else:
    print("No obvious filename column found.")

print("\nClass counts:")
for i in load.columns:
    if any(j in i.lower() for j in ["label", "class", "category", "defect"]):
        print(f"\n{i}:")
        print(load[i].value_counts(dropna=False).to_string())

print("\nSplit counts:")
for i in load.columns:
    if "split" in i.lower():
        print(load[i].value_counts(dropna=False).to_string())

Shape: (12064, 3)

Columns:
['image', 'label', 'split']

First 10 rows:

           image       label  split
0  Hefei1750.jpg       crack  train
1  Hefei3568.jpg       crack   test
2   Hefei206.jpg   corrosion  train
3  Hefei7694.jpg       crack  train
4  Hefei2910.jpg     leakage  train
5  Hefei7075.jpg     leakage   test
6  Hefei5711.jpg       crack   test
7  Hefei5512.jpg       crack  train
8  Hefei3628.jpg       crack  train
9  Hefei8755.jpg  abscission  train

Filename examples:
['Hefei7104.jpg', 'Hefei4957.jpg', 'Hefei11994.jpg', 'Hefei327.jpg', 'Hefei2465.jpg', 'Hefei183.jpg', 'Hefei5643.jpg', 'Hefei5613.jpg', 'Hefei9450.jpg', 'Hefei4969.jpg', 'Hefei4173.jpg', 'Hefei10515.jpg', 'Hefei1156.jpg', 'Hefei9689.jpg', 'Hefei3063.jpg', 'Hefei88.jpg', 'Hefei5083.jpg', 'Hefei11719.jpg', 'Hefei3404.jpg', 'Hefei4805.jpg']

Class counts:

label:
label
crack         4363
abscission    3340
leakage       1949
corrosion     1662
bulge          750

Split counts:
split
train         9647
validation    1214
test          1203

In [37]:
import pandas as pd
import numpy as np
import re

from pathlib import Path
from sklearn.model_selection import StratifiedGroupKFold

project_dir = Path("/content/drive/MyDrive/DistributedAIProject")
input_path = project_dir / "mbdd_classification_manifest_deduplicated.csv"
output_path = project_dir / "mbdd_sequence_split_candidate.csv"

load = pd.read_csv(input_path).copy()

In [38]:
# Extract the numeric sequence ID from filenames such as Hefei1750.jpg
def get_sequence_number(filename):
    match = re.fullmatch(r"Hefei(\d+)\.jpg", str(filename), flags=re.IGNORECASE)
    return int(match.group(1)) if match else None

load["sequence_number"] = load["image"].apply(get_sequence_number)

if load["sequence_number"].isna().any():
    raise ValueError("Some filenames do not match the expected Hefei<number>.jpg pattern.")

In [39]:
# Group consecutive numbers together.
# A gap greater than 1 starts a new group.
ordered = load[["image", "sequence_number"]].sort_values("sequence_number")
group_by_image = {}
group_id = -1
previous_number = None

for i in ordered.itertuples(index=False):
    number = int(i.sequence_number)
    if previous_number is None or number != previous_number + 1:
        group_id = group_id+1

    group_by_image[i.image] = group_id
    previous_number = number

load["sequence_group"] = load["image"].map(group_by_image)

In [40]:
# Approximate the original 80/10/10 split using grouped stratification.
outer = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
train, temp = next(outer.split(load, y=load["label"], groups=load["sequence_group"]))

load["new_split"] = ""
load.loc[train, "new_split"] = "train"

temp = load.iloc[temp].copy()

In [41]:
# Splitting the temporary 20% approximately equally into validation and test.
inner = StratifiedGroupKFold(n_splits=2, shuffle=True, random_state=43)
validation, test = next(inner.split(temp, y=temp["label"], groups=temp["sequence_group"]))

load.loc[temp.iloc[validation].index, "new_split"] = "validation"
load.loc[temp.iloc[test].index, "new_split"] = "test"

In [42]:
# Save a clean candidate manifest, retaining only the required columns.
candidate = load[["image", "label", "new_split"]].rename(columns={"new_split": "split"})
candidate.to_csv(output_path, index=False)

print("Saved candidate: ", output_path)
print("\nSplit sizes: ")
print(candidate["split"].value_counts())

print("\nClass distribution by split: ")
print(pd.crosstab(candidate["label"], candidate["split"]))

# Verify that no sequence group crosses split boundaries.
check = load.groupby("sequence_group")["new_split"].nunique()
print("\nGroups crossing splits: ", int((check > 1).sum()))
print("Total images: ", len(candidate))
print("Unique filenames: ", candidate["image"].nunique())

Saved candidate:  /content/drive/MyDrive/DistributedAIProject/mbdd_sequence_split_candidate.csv

Split sizes:
split
train         9222
validation    2774
test            68
Name: count, dtype: int64

Class distribution by split:
split       test  train  validation
label
abscission    68   2523         749
bulge          0      0         750
corrosion      0   1662           0
crack          0   3684         679
leakage        0   1353         596

Groups crossing splits:  0
Total images:  12064
Unique filenames:  12064

In [45]:
import pandas as pd
import re
from pathlib import Path

project_dir = Path("/content/drive/MyDrive/DistributedAIProject")
load = pd.read_csv(project_dir / "mbdd_classification_manifest_deduplicated.csv")

load["sequence_number"] = load["image"].str.extract(r"^Hefei(\d+)\.jpg$", expand=False).astype(int)

ordered = load.sort_values("sequence_number").copy()
ordered["gap"] = ordered["sequence_number"].diff()
ordered["group_id"] = ordered["gap"].ne(1).cumsum()

groups = ordered.groupby("group_id").agg(
    group_size=("image", "size"),
    first=("sequence_number", "min"),
    last=("sequence_number", "max"),
    classes=("label", "nunique")
)

print("Number of groups:", len(groups))
print("\nGroup-size summary:")
print(groups["group_size"].describe())

print("\nLargest groups:")
display(groups.sort_values("group_size", ascending=False).head(15))

print("\nClasses in largest groups:")
largest_idx = groups.nlargest(10, "group_size").index
display(ordered[ordered["group_id"].isin(largest_idx)].groupby("group_id").agg(
        size=("image", "size"),
        classes=("label", lambda x: ", ".join(sorted(x.unique()))),
        first=("image", "first"),
        last=("image", "last")
    ).sort_values("size", ascending=False))

Number of groups: 80

Group-size summary:
count      80.000000
mean      150.800000
std       307.079605
min         1.000000
25%        11.750000
50%        34.000000
75%       125.250000
max      1889.000000
Name: group_size, dtype: float64

Largest groups:

          group_size  first   last  classes
group_id
10              1889   3352   5240        4
12              1509   5397   6905        1
6                838   1822   2659        2
4                707   1018   1724        4
20               677   9029   9705        2
13               632   6936   7567        2
2                475    426    900        2
1                424      1    424        1
19               361   8667   9027        2
45               342  11693  12034        1
23               336   9845  10180        1
15               336   7820   8155        1
34               309  10675  10983        2
7                286   2662   2947        2
18               231   8347   8577        1

Classes in largest groups:

,size,classes,first,last
group_id,,,,
10,1889,"abscission, bulge, crack, leakage",Hefei3352.jpg,Hefei5240.jpg
12,1509,crack,Hefei5397.jpg,Hefei6905.jpg
6,838,"crack, leakage",Hefei1822.jpg,Hefei2659.jpg
4,707,"abscission, corrosion, crack, leakage",Hefei1018.jpg,Hefei1724.jpg
20,677,"abscission, crack",Hefei9029.jpg,Hefei9705.jpg
13,632,"abscission, leakage",Hefei6936.jpg,Hefei7567.jpg
2,475,"corrosion, leakage",Hefei426.jpg,Hefei900.jpg
1,424,corrosion,Hefei1.jpg,Hefei424.jpg
19,361,"abscission, leakage",Hefei8667.jpg,Hefei9027.jpg
45,342,abscission,Hefei11693.jpg,Hefei12034.jpg

## Final Validation Summary

### Dataset
- Dataset: MBDD2025
- Total images selected: 12,064
- Task: 5-class, single-label image classification
- Classes: abscission, bulge, corrosion, crack, leakage
- Annotation source: VOC XML annotations

### Dataset preparation and validation
- Selected images with exactly one distinct damage category.
- Excluded multi-category images from this single-label experiment.
- Generated an 80/10/10 train-validation-test split.
- Computed SHA-256 hashes to detect exact duplicate images.
- Corrected the split to prevent exact duplicate images from crossing splits.
- Verified 12,064 rows, unique filenames, no missing values, and all five classes across the splits.

### Final split
- Train: 9,647 images
- Validation: 1,214 images
- Test: 1,203 images

### Limitations
- Consecutive Hefei filenames showed potentially related captures in different splits.
- Filename adjacency alone does not establish visual similarity.
- A naive sequence-grouping attempt produced a severely imbalanced split and was rejected.
- Exact duplicate leakage was checked; all possible near-duplicate leakage has not been ruled out.

### Next stage
Prepare reproducible image preprocessing and train the custom CNN baseline, followed by ResNet18 using the same split and evaluation protocol.